# ../celer_sight_ai/UiAssets/NewMenuOld.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(610, 947)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.gridLayout_8 = QtWidgets.QGridLayout(Form)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.CreateNewVButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.CreateNewVButton.sizePolicy().hasHeightForWidth()
        )
        self.CreateNewVButton.setSizePolicy(sizePolicy)
        self.CreateNewVButton.setMaximumSize(QtCore.QSize(316, 40))
        self.CreateNewVButton.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,200);  \n"
            "background-color: #1D1D1D;  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid;  \n"
            "border-radius: 13;  \n"
            "padding: 3px;  \n"
            "font-size: 22px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            "\n"
            "QPushButton:hover{  \n"
            "color: rgb(25,25,25);\n"
            "background-color: rgb(255,255,255);  \n"
            "border-width: 2px;  \n"
            "border-style: solid;  \n"
            "border-radius: 13;  \n"
            "padding: 3px;  \n"
            "font-size: 22px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            ""
        )
        self.CreateNewVButton.setObjectName("CreateNewVButton")
        self.gridLayout.addWidget(self.CreateNewVButton, 2, 0, 1, 1)
        self.OpenButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenButton.sizePolicy().hasHeightForWidth())
        self.OpenButton.setSizePolicy(sizePolicy)
        self.OpenButton.setMaximumSize(QtCore.QSize(305, 40))
        self.OpenButton.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,200);  \n"
            "background-color: #1D1D1D;  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid;  \n"
            "border-radius: 13;  \n"
            "padding: 3px;  \n"
            "font-size: 22px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            "\n"
            "QPushButton:hover{  \n"
            "color: rgb(25,25,25);\n"
            "background-color: rgb(255,255,255);  \n"
            "border-width: 2px;  \n"
            "border-style: solid;  \n"
            "border-radius: 13;  \n"
            "padding: 3px;  \n"
            "font-size: 22px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            ""
        )
        self.OpenButton.setObjectName("OpenButton")
        self.gridLayout.addWidget(self.OpenButton, 2, 1, 1, 1)
        self.AnalysisTypeFrame = QtWidgets.QFrame(parent=self.frame)
        self.AnalysisTypeFrame.setStyleSheet(
            "QFrame#AnalysisTypeFrame\n"
            "{\n"
            "color: rgba(255,255,255,00);  \n"
            "border-width: 0px;  \n"
            "border-color: rgb(25,25,25);  \n"
            "border-style: solid;  \n"
            "border-radius: 0;  \n"
            "font-size: 22px;  \n"
            "background-color: rgba(100, 100, 100,0);\n"
            "}"
        )
        self.AnalysisTypeFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.AnalysisTypeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.AnalysisTypeFrame.setObjectName("AnalysisTypeFrame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.AnalysisTypeFrame)
        self.gridLayout_16.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_16.setSpacing(4)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.AnalysisTypeContextsFrame = QtWidgets.QFrame(parent=self.AnalysisTypeFrame)
        self.AnalysisTypeContextsFrame.setStyleSheet(
            "QFrame#AnalysisTypeContextsFrame{\n"
            "color: rgb(25,25,25);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(25,25,25);  \n"
            "border-style: solid;  \n"
            "    border-top-left-radius: 0px;\n"
            "    border-bottom-left-radius: 10px;\n"
            "    border-top-right-radius: 0px;\n"
            "    border-bottom-right-radius:10px; \n"
            "font-size: 22px;  \n"
            "background-color: rgb(25,25,25);\n"
            "}"
        )
        self.AnalysisTypeContextsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.AnalysisTypeContextsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.AnalysisTypeContextsFrame.setObjectName("AnalysisTypeContextsFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.AnalysisTypeContextsFrame)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.AnalysisTypeContextsFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(54, 0))
        self.line.setMaximumSize(QtCore.QSize(74, 2))
        self.line.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_4.addItem(spacerItem1, 2, 2, 1, 1)
        self.AnalysisDialog_RGB_selectionFrame = QtWidgets.QFrame(
            parent=self.AnalysisTypeContextsFrame
        )
        self.AnalysisDialog_RGB_selectionFrame.setMaximumSize(
            QtCore.QSize(16777215, 111)
        )
        self.AnalysisDialog_RGB_selectionFrame.setStyleSheet(
            "QFrame#AnalysisDialog_RGB_selectionFrame{\n"
            "color: rgba(255,255,255,100);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(25,25,25);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "font-size: 22px;  \n"
            "background-color: rgba(0, 0, 0,0);\n"
            "}"
        )
        self.AnalysisDialog_RGB_selectionFrame.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.AnalysisDialog_RGB_selectionFrame.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.AnalysisDialog_RGB_selectionFrame.setObjectName(
            "AnalysisDialog_RGB_selectionFrame"
        )
        self.gridLayout_6 = QtWidgets.QGridLayout(
            self.AnalysisDialog_RGB_selectionFrame
        )
        self.gridLayout_6.setContentsMargins(20, 0, 20, 0)
        self.gridLayout_6.setHorizontalSpacing(10)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        self.SourceChannelsButton = QtWidgets.QPushButton(
            parent=self.AnalysisDialog_RGB_selectionFrame
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SourceChannelsButton.sizePolicy().hasHeightForWidth()
        )
        self.SourceChannelsButton.setSizePolicy(sizePolicy)
        self.SourceChannelsButton.setMaximumSize(QtCore.QSize(250, 40))
        self.SourceChannelsButton.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,200);  \n"
            "background-color: rgba(0,0,0,0); \n"
            "border-color:rgba(0,0,0,0);\n"
            "border-width: 2px;  \n"
            "border-style: solid;  \n"
            "border-radius:6;  \n"
            "padding: 3px;  \n"
            "font-size: 22px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            "\n"
            ""
        )
        self.SourceChannelsButton.setObjectName("SourceChannelsButton")
        self.gridLayout_6.addWidget(self.SourceChannelsButton, 0, 0, 1, 1)
        self.BFrame = QtWidgets.QFrame(parent=self.AnalysisDialog_RGB_selectionFrame)
        self.BFrame.setMinimumSize(QtCore.QSize(49, 0))
        self.BFrame.setMaximumSize(QtCore.QSize(10000, 43))
        self.BFrame.setStyleSheet(
            "             background-color:rgb(0,0,210);  \n"
            "             border-width: 2px;  \n"
            "             border-color: #ABABAB;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 15;  \n"
            "             padding: 4px;  \n"
            "\n"
            " "
        )
        self.BFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BFrame.setObjectName("BFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.BFrame)
        self.gridLayout_7.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.GBtn_3 = QtWidgets.QPushButton(parent=self.BFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBtn_3.sizePolicy().hasHeightForWidth())
        self.GBtn_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.GBtn_3.setFont(font)
        self.GBtn_3.setStyleSheet(
            "QPushButton{color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(80,80,200);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            "\n"
            "QPushButton:hover{color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(80,80,250);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}"
        )
        self.GBtn_3.setObjectName("GBtn_3")
        self.gridLayout_7.addWidget(self.GBtn_3, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.BFrame, 0, 4, 1, 1)
        self.RFrame = QtWidgets.QFrame(parent=self.AnalysisDialog_RGB_selectionFrame)
        self.RFrame.setMinimumSize(QtCore.QSize(49, 0))
        self.RFrame.setMaximumSize(QtCore.QSize(10000, 43))
        self.RFrame.setStyleSheet(
            "             background-color: rgb(210,0,0);  \n"
            "             border-width: 2px;  \n"
            "             border-color: #ABABAB;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 15;  \n"
            "             padding: 4px;  \n"
            "\n"
            " "
        )
        self.RFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RFrame.setObjectName("RFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.RFrame)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RBtn = QtWidgets.QPushButton(parent=self.RFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBtn.sizePolicy().hasHeightForWidth())
        self.RBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RBtn.setFont(font)
        self.RBtn.setStyleSheet(
            "QPushButton{\n"
            "color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(200,80,80);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;\n"
            "}  \n"
            "\n"
            "QPushButton:hover{\n"
            "color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(250,80,80);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;\n"
            "}  "
        )
        self.RBtn.setObjectName("RBtn")
        self.gridLayout_3.addWidget(self.RBtn, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.RFrame, 0, 2, 1, 1)
        self.GFrame = QtWidgets.QFrame(parent=self.AnalysisDialog_RGB_selectionFrame)
        self.GFrame.setMinimumSize(QtCore.QSize(49, 0))
        self.GFrame.setMaximumSize(QtCore.QSize(10000, 43))
        self.GFrame.setStyleSheet(
            "             background-color:rgb(0,210,0);  \n"
            "             border-width: 2px;  \n"
            "             border-color: #ABABAB;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 15;  \n"
            "             padding: 4px;  \n"
            "\n"
            " "
        )
        self.GFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.GFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.GFrame.setObjectName("GFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.GFrame)
        self.gridLayout_5.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.GBtn_2 = QtWidgets.QPushButton(parent=self.GFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBtn_2.sizePolicy().hasHeightForWidth())
        self.GBtn_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.GBtn_2.setFont(font)
        self.GBtn_2.setStyleSheet(
            "\n"
            "\n"
            "QPushButton:hover{\n"
            "color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(80,225,80);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            "QPushButton{\n"
            "color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(80,200,80);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}"
        )
        self.GBtn_2.setObjectName("GBtn_2")
        self.gridLayout_5.addWidget(self.GBtn_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.GFrame, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.AnalysisDialog_RGB_selectionFrame, 1, 0, 1, 3)
        self.AnalysisDialog_RGB_selectionFrame_2 = QtWidgets.QFrame(
            parent=self.AnalysisTypeContextsFrame
        )
        self.AnalysisDialog_RGB_selectionFrame_2.setMaximumSize(
            QtCore.QSize(16777215, 70)
        )
        self.AnalysisDialog_RGB_selectionFrame_2.setStyleSheet(
            "QFrame#AnalysisDialog_RGB_selectionFrame_2\n"
            "{\n"
            "color: rgba(255,255,255,100);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(25,25,25);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "font-size: 22px;  \n"
            "background-color: rgba(0, 0, 0,0);\n"
            "}"
        )
        self.AnalysisDialog_RGB_selectionFrame_2.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.AnalysisDialog_RGB_selectionFrame_2.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.AnalysisDialog_RGB_selectionFrame_2.setObjectName(
            "AnalysisDialog_RGB_selectionFrame_2"
        )
        self.gridLayout_17 = QtWidgets.QGridLayout(
            self.AnalysisDialog_RGB_selectionFrame_2
        )
        self.gridLayout_17.setContentsMargins(20, 0, 20, 0)
        self.gridLayout_17.setHorizontalSpacing(10)
        self.gridLayout_17.setVerticalSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.BFrame_2 = QtWidgets.QFrame(
            parent=self.AnalysisDialog_RGB_selectionFrame_2
        )
        self.BFrame_2.setMinimumSize(QtCore.QSize(49, 0))
        self.BFrame_2.setMaximumSize(QtCore.QSize(10000, 43))
        self.BFrame_2.setStyleSheet(
            "             background-color:rgb(0,0,210);  \n"
            "             border-width: 2px;  \n"
            "             border-color: #ABABAB;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 15;  \n"
            "             padding: 4px;  \n"
            "\n"
            " "
        )
        self.BFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BFrame_2.setObjectName("BFrame_2")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.BFrame_2)
        self.gridLayout_20.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.GBtn_5 = QtWidgets.QPushButton(parent=self.BFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBtn_5.sizePolicy().hasHeightForWidth())
        self.GBtn_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.GBtn_5.setFont(font)
        self.GBtn_5.setStyleSheet(
            "QPushButton{color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(80,80,200);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            "\n"
            "QPushButton:hover{color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(80,80,250);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}"
        )
        self.GBtn_5.setObjectName("GBtn_5")
        self.gridLayout_20.addWidget(self.GBtn_5, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.BFrame_2, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_17.addItem(spacerItem3, 0, 1, 1, 1)
        self.MeasureOnButton = QtWidgets.QPushButton(
            parent=self.AnalysisDialog_RGB_selectionFrame_2
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.MeasureOnButton.sizePolicy().hasHeightForWidth()
        )
        self.MeasureOnButton.setSizePolicy(sizePolicy)
        self.MeasureOnButton.setMaximumSize(QtCore.QSize(250, 40))
        self.MeasureOnButton.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,200);  \n"
            "background-color: rgba(0,0,0,0); \n"
            "border-color:rgba(0,0,0,0);\n"
            "border-width: 2px;  \n"
            "border-style: solid;  \n"
            "border-radius:6;  \n"
            "padding: 3px;  \n"
            "font-size: 22px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            "\n"
            ""
        )
        self.MeasureOnButton.setObjectName("MeasureOnButton")
        self.gridLayout_17.addWidget(self.MeasureOnButton, 0, 0, 1, 1)
        self.RFrame_2 = QtWidgets.QFrame(
            parent=self.AnalysisDialog_RGB_selectionFrame_2
        )
        self.RFrame_2.setMinimumSize(QtCore.QSize(49, 0))
        self.RFrame_2.setMaximumSize(QtCore.QSize(10000, 43))
        self.RFrame_2.setStyleSheet(
            "             background-color: rgb(210,0,0);  \n"
            "             border-width: 2px;  \n"
            "             border-color: #ABABAB;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 15;  \n"
            "             padding: 4px;  \n"
            "\n"
            " "
        )
        self.RFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RFrame_2.setObjectName("RFrame_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.RFrame_2)
        self.gridLayout_18.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.RBtn_2 = QtWidgets.QPushButton(parent=self.RFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RBtn_2.sizePolicy().hasHeightForWidth())
        self.RBtn_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.RBtn_2.setFont(font)
        self.RBtn_2.setStyleSheet(
            "QPushButton{\n"
            "color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(200,80,80);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;\n"
            "}  \n"
            "\n"
            "QPushButton:hover{\n"
            "color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(250,80,80);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;\n"
            "}  "
        )
        self.RBtn_2.setObjectName("RBtn_2")
        self.gridLayout_18.addWidget(self.RBtn_2, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.RFrame_2, 0, 2, 1, 1)
        self.GFrame_2 = QtWidgets.QFrame(
            parent=self.AnalysisDialog_RGB_selectionFrame_2
        )
        self.GFrame_2.setMinimumSize(QtCore.QSize(49, 0))
        self.GFrame_2.setMaximumSize(QtCore.QSize(10000, 43))
        self.GFrame_2.setStyleSheet(
            "             background-color:rgb(0,210,0);  \n"
            "             border-width: 2px;  \n"
            "             border-color: #ABABAB;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 15;  \n"
            "             padding: 4px;  \n"
            "\n"
            " "
        )
        self.GFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.GFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.GFrame_2.setObjectName("GFrame_2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.GFrame_2)
        self.gridLayout_19.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.GBtn_4 = QtWidgets.QPushButton(parent=self.GFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBtn_4.sizePolicy().hasHeightForWidth())
        self.GBtn_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.GBtn_4.setFont(font)
        self.GBtn_4.setStyleSheet(
            "\n"
            "\n"
            "QPushButton:hover{\n"
            "color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(80,225,80);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}\n"
            "QPushButton{\n"
            "color: white;  \n"
            "background-color: rgba(0,0,0,120);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(80,200,80);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "padding: 3px;  \n"
            "font-size: 25px;  \n"
            "padding-left: 5px;  \n"
            "padding-right: 5px;  \n"
            "}"
        )
        self.GBtn_4.setObjectName("GBtn_4")
        self.gridLayout_19.addWidget(self.GBtn_4, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.GFrame_2, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(
            self.AnalysisDialog_RGB_selectionFrame_2, 3, 0, 1, 3
        )
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.AnalysisTypeContextsFrame)
        self.textBrowser.setStyleSheet(
            "color: rgb(255, 255, 255);\n"
            "\n"
            "border-width: 2px;  \n"
            "border-color: rgba(25,25,25,0);  \n"
            "border-style: solid;  \n"
            "border-radius: 10;  \n"
            "font-size: 22px;  \n"
            "background-color: rgba(0, 0, 0,0);\n"
            ""
        )
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 4, 0, 1, 3)
        self.gridLayout_16.addWidget(self.AnalysisTypeContextsFrame, 1, 0, 1, 3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.AnalysisTypeFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_16.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.AnalysisTypeFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet(
            "QComboBox\n"
            "{\n"
            "    subcontrol-origin: padding;\n"
            "    subcontrol-position: top right;\n"
            "    selection-background-color: #111;\n"
            "    selection-color: yellow;\n"
            "    color: white;\n"
            "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
            "    border-style: solid;\n"
            "    border: 1px solid #1e1e1e;\n"
            "    border-radius: 5;\n"
            "    padding: 1px 0px 1px 20px;\n"
            "}\n"
            "\n"
            "\n"
            "QComboBox:hover, QPushButton:hover\n"
            "{\n"
            "    border: 1px solid yellow;\n"
            "    color: white;\n"
            "}\n"
            "\n"
            "QComboBox:editable {\n"
            "    background: red;\n"
            "    color: pink;\n"
            "}\n"
            "\n"
            "QComboBox:on\n"
            "{\n"
            "    padding-top: 0px;\n"
            "    padding-left: 0px;\n"
            "    color: white;\n"
            "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
            "    selection-background-color: #ffaa00;\n"
            "}\n"
            "\n"
            "QComboBox:!on\n"
            "{\n"
            "    color: white;\n"
            "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #666, stop: 0.1 #555, stop: 0.5 #555, stop: 0.9 #444, stop: 1 #333);\n"
            "}\n"
            "\n"
            "QComboBox QAbstractItemView\n"
            "{\n"
            "    border: 2px solid darkgray;\n"
            "    color: black;\n"
            "    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #111, stop: 1 #333);\n"
            "}\n"
            "\n"
            "QComboBox::drop-down\n"
            "{\n"
            "     subcontrol-origin: padding;\n"
            "     subcontrol-position: top right;\n"
            "     width: 15px;\n"
            "     color: white;\n"
            "     border-left-width: 0px;\n"
            "     border-left-color: darkgray;\n"
            "     border-left-style: solid; /* just a single line */\n"
            "     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
            "     border-bottom-right-radius: 3px;\n"
            "     padding-left: 10px;\n"
            " }\n"
            "\n"
            "QComboBox::down-arrow, QSpinBox::down-arrow, QTimeEdit::down-arrow, QDateEdit::down-arrow\n"
            "{\n"
            "     image: url(:/icons/down_arrow.png);\n"
            "     width: 7px;\n"
            "     height: 5px;\n"
            "}"
        )
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_16.addWidget(self.comboBox, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.AnalysisTypeFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_16.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.AnalysisTypeFrame, 1, 0, 1, 2)
        self.RegionSelectionFrame = QtWidgets.QFrame(parent=self.frame)
        self.RegionSelectionFrame.setMinimumSize(QtCore.QSize(300, 400))
        self.RegionSelectionFrame.setStyleSheet(
            "QFrame#RegionSelectionFrame{\n"
            "color: rgba(255,255,255,100);  \n"
            "border-width: 1px;  \n"
            "border-color: rgb(25,25,25);  \n"
            "border-style: solid;  \n"
            "border-radius: 4;  \n"
            "font-size: 22px;  \n"
            "background-color: rgba(0, 0, 0,40);\n"
            "\n"
            "}"
        )
        self.RegionSelectionFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RegionSelectionFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RegionSelectionFrame.setObjectName("RegionSelectionFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.RegionSelectionFrame)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.EmbryoFrame = QtWidgets.QFrame(parent=self.RegionSelectionFrame)
        self.EmbryoFrame.setStyleSheet(
            "QFrame{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(0,0,0);  \n"
            "border-style: solid; \n"
            "}\n"
            "QFrame:hover{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid; \n"
            "}"
        )
        self.EmbryoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.EmbryoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.EmbryoFrame.setObjectName("EmbryoFrame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.EmbryoFrame)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.EmbryoBtn = QtWidgets.QPushButton(parent=self.EmbryoFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmbryoBtn.sizePolicy().hasHeightForWidth())
        self.EmbryoBtn.setSizePolicy(sizePolicy)
        self.EmbryoBtn.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,100);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid;  \n"
            "border-radius: 2;  \n"
            "font-size: 22px;  \n"
            "border-image: url(C:/Users/Manos/Documents/EmbryoSample.tif);\n"
            "background-position: center;\n"
            "background-size: cover;\n"
            "}\n"
            "QPushButton:hover{\n"
            "color: rgba(255,255,255,255)\n"
            "}"
        )
        self.EmbryoBtn.setObjectName("EmbryoBtn")
        self.gridLayout_9.addWidget(self.EmbryoBtn, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.EmbryoFrame, 0, 1, 1, 1)
        self.WholeBodyFrame = QtWidgets.QFrame(parent=self.RegionSelectionFrame)
        self.WholeBodyFrame.setStyleSheet(
            "QFrame{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(0,0,0);  \n"
            "border-style: solid; \n"
            "}\n"
            "QFrame:hover{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid; \n"
            "}"
        )
        self.WholeBodyFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.WholeBodyFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.WholeBodyFrame.setObjectName("WholeBodyFrame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.WholeBodyFrame)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.WholeBodyBtn = QtWidgets.QPushButton(parent=self.WholeBodyFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WholeBodyBtn.sizePolicy().hasHeightForWidth())
        self.WholeBodyBtn.setSizePolicy(sizePolicy)
        self.WholeBodyBtn.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,100);  \n"
            " \n"
            "border-radius: 2;  \n"
            "font-size: 22px;  \n"
            "border-image: url(C:/Users/Manos/Documents/WholeBody.tif);\n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid; \n"
            "background-position: center;\n"
            "background-size: cover;\n"
            "}\n"
            "QPushButton:hover{\n"
            "color: rgba(255,255,255,255);  \n"
            " \n"
            "border-radius: 2;  \n"
            "font-size: 22px;  \n"
            "border-image: url(C:/Users/Manos/Documents/WholeBody.tif);\n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid; \n"
            "background-position: center;\n"
            "background-size: cover;\n"
            "}"
        )
        self.WholeBodyBtn.setObjectName("WholeBodyBtn")
        self.gridLayout_10.addWidget(self.WholeBodyBtn, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.WholeBodyFrame, 0, 0, 1, 1)
        self.MuscleFrame = QtWidgets.QFrame(parent=self.RegionSelectionFrame)
        self.MuscleFrame.setStyleSheet(
            "QFrame{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(0,0,0);  \n"
            "border-style: solid; \n"
            "}\n"
            "QFrame:hover{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid; \n"
            "}"
        )
        self.MuscleFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.MuscleFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.MuscleFrame.setObjectName("MuscleFrame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.MuscleFrame)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.MuscleBtn = QtWidgets.QPushButton(parent=self.MuscleFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MuscleBtn.sizePolicy().hasHeightForWidth())
        self.MuscleBtn.setSizePolicy(sizePolicy)
        self.MuscleBtn.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,100);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid;  \n"
            "border-radius: 2;  \n"
            "font-size: 22px;  \n"
            "border-image: url(C:/Users/Manos/Documents/MuscleSample.tif);\n"
            "background-position: center;\n"
            "background-size: cover;\n"
            "}\n"
            "QPushButton:hover{\n"
            "color: rgba(255,255,255,255);\n"
            "}"
        )
        self.MuscleBtn.setObjectName("MuscleBtn")
        self.gridLayout_11.addWidget(self.MuscleBtn, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.MuscleFrame, 1, 1, 1, 1)
        self.HeadFame = QtWidgets.QFrame(parent=self.RegionSelectionFrame)
        self.HeadFame.setStyleSheet(
            "QFrame{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(0,0,0);  \n"
            "border-style: solid; \n"
            "}\n"
            "QFrame:hover{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid; \n"
            "}"
        )
        self.HeadFame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.HeadFame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.HeadFame.setObjectName("HeadFame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.HeadFame)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.HeadBtn = QtWidgets.QPushButton(parent=self.HeadFame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HeadBtn.sizePolicy().hasHeightForWidth())
        self.HeadBtn.setSizePolicy(sizePolicy)
        self.HeadBtn.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,100);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid;  \n"
            "border-radius: 2;  \n"
            "font-size: 22px;  \n"
            "border-image: url(C:/Users/Manos/Documents/headSample2.tif);\n"
            "background-position: center;\n"
            "background-size: cover;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "color: rgba(255,255,255,255);\n"
            "}"
        )
        self.HeadBtn.setObjectName("HeadBtn")
        self.gridLayout_12.addWidget(self.HeadBtn, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.HeadFame, 1, 0, 1, 1)
        self.IntestineFrame = QtWidgets.QFrame(parent=self.RegionSelectionFrame)
        self.IntestineFrame.setStyleSheet(
            "QFrame{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(0,0,0);  \n"
            "border-style: solid; \n"
            "}\n"
            "QFrame:hover{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid; \n"
            "}"
        )
        self.IntestineFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.IntestineFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.IntestineFrame.setObjectName("IntestineFrame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.IntestineFrame)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.IntenstineBtn = QtWidgets.QPushButton(parent=self.IntestineFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.IntenstineBtn.sizePolicy().hasHeightForWidth()
        )
        self.IntenstineBtn.setSizePolicy(sizePolicy)
        self.IntenstineBtn.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,100);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid;  \n"
            "border-radius: 2;  \n"
            "font-size: 22px;  \n"
            "border-image: url(C:/Users/Manos/Documents/Intestine.tif);\n"
            "background-position: center;\n"
            "background-size: cover;\n"
            "}\n"
            "QPushButton:hover{\n"
            "\n"
            "color:rgba(255,255,255,255);\n"
            "}"
        )
        self.IntenstineBtn.setObjectName("IntenstineBtn")
        self.gridLayout_13.addWidget(self.IntenstineBtn, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.IntestineFrame, 0, 2, 1, 1)
        self.SeamFrame = QtWidgets.QFrame(parent=self.RegionSelectionFrame)
        self.SeamFrame.setStyleSheet(
            "QFrame{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(0,0,0);  \n"
            "border-style: solid; \n"
            "}\n"
            "QFrame:hover{\n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid; \n"
            "}"
        )
        self.SeamFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SeamFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SeamFrame.setObjectName("SeamFrame")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.SeamFrame)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.SeamBtn = QtWidgets.QPushButton(parent=self.SeamFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SeamBtn.sizePolicy().hasHeightForWidth())
        self.SeamBtn.setSizePolicy(sizePolicy)
        self.SeamBtn.setStyleSheet(
            "QPushButton{\n"
            "color: rgba(255,255,255,100);  \n"
            "border-width: 2px;  \n"
            "border-color: rgb(225,225,225);  \n"
            "border-style: solid;  \n"
            "border-radius: 2;  \n"
            "font-size: 22px;  \n"
            "border-image: url(C:/Users/Manos/Documents/MuscleSample.tif);\n"
            "background-position: center;\n"
            "background-size: cover;\n"
            "}\n"
            "QPushButton:hover{\n"
            "color: rgba(255,255,255,255);\n"
            "}"
        )
        self.SeamBtn.setObjectName("SeamBtn")
        self.gridLayout_14.addWidget(self.SeamBtn, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.SeamFrame, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.RegionSelectionFrame, 0, 0, 1, 2)
        self.gridLayout_8.addWidget(self.frame, 1, 0, 1, 1)
        self.FrameForWindow = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.FrameForWindow.sizePolicy().hasHeightForWidth()
        )
        self.FrameForWindow.setSizePolicy(sizePolicy)
        self.FrameForWindow.setMinimumSize(QtCore.QSize(0, 39))
        self.FrameForWindow.setMaximumSize(QtCore.QSize(16777215, 20))
        self.FrameForWindow.setStyleSheet("")
        self.FrameForWindow.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FrameForWindow.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FrameForWindow.setObjectName("FrameForWindow")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.FrameForWindow)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.FrameWidget = QtWidgets.QWidget(parent=self.FrameForWindow)
        self.FrameWidget.setObjectName("FrameWidget")
        self.gridLayout_15.addWidget(self.FrameWidget, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.FrameForWindow, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CreateNewVButton.setText(_translate("Form", "Create New"))
        self.OpenButton.setText(_translate("Form", "Open"))
        self.SourceChannelsButton.setText(_translate("Form", "Source Channels"))
        self.GBtn_3.setText(_translate("Form", "B"))
        self.RBtn.setText(_translate("Form", "R"))
        self.GBtn_2.setText(_translate("Form", "G"))
        self.GBtn_5.setText(_translate("Form", "B"))
        self.MeasureOnButton.setText(_translate("Form", "Measure On"))
        self.RBtn_2.setText(_translate("Form", "R"))
        self.GBtn_4.setText(_translate("Form", "G"))
        self.textBrowser.setHtml(
            _translate(
                "Form",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:22px; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:16pt;">&quot;Analysis Type&quot; on images with channels &quot;channel 1&quot;+ &quot; Channel 2&quot;  and the  &quot;Analysis spesific measurment&quot; is measured on the channel &quot;channel 1&quot;..</span></p></body></html>',
            )
        )
        self.pushButton_4.setText(_translate("Form", "-"))
        self.comboBox.setItemText(0, _translate("Form", "AnalysisType"))
        self.comboBox.setItemText(1, _translate("Form", "Intensity Analysis"))
        self.comboBox.setItemText(2, _translate("Form", "Fragmentation Analysis"))
        self.comboBox.setItemText(3, _translate("Form", "Aggregates Analysis"))
        self.pushButton_3.setText(_translate("Form", "+"))
        self.EmbryoBtn.setText(_translate("Form", "Embryo"))
        self.WholeBodyBtn.setText(_translate("Form", "Whole Body"))
        self.MuscleBtn.setText(_translate("Form", "Muscle"))
        self.HeadBtn.setText(_translate("Form", "Head"))
        self.IntenstineBtn.setText(_translate("Form", "Intenstine"))
        self.SeamBtn.setText(_translate("Form", "Seam"))
