# ../celer_sight_ai/UiAssets/NewMenu_tutorial.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(608, 174)
        Form.setStyleSheet("QWidget{\n" "background-color:rgba(0,0,0,255);}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setStyleSheet(
            "QFrame{\n"
            "background-color:rgba(245,245,245);\n"
            "border-radius:10px;\n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CreateNewVButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.CreateNewVButton.sizePolicy().hasHeightForWidth()
        )
        self.CreateNewVButton.setSizePolicy(sizePolicy)
        self.CreateNewVButton.setMinimumSize(QtCore.QSize(130, 35))
        self.CreateNewVButton.setMaximumSize(QtCore.QSize(130, 35))
        self.CreateNewVButton.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.CreateNewVButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.CreateNewVButton.setStyleSheet(
            "QPushButton{\n"
            '    border-image: url("data/icons/icons_aa_tool/procced_nm_normal.png") 0 0 0 0 stretch stretch;\n'
            "\n"
            '    font-family:"Lato";\n'
            "    font-size: 19px;\n"
            "    border: 1px solid;\n"
            "    color: rgba(250, 250, 250,255);\n"
            "    border:0px solid;\n"
            "\n"
            "\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover{\n"
            '    border-image: url("data/icons/icons_aa_tool/procced_nm_hover.png") 0 0 0 0 stretch stretch;\n'
            "\n"
            "}"
        )
        self.CreateNewVButton.setObjectName("CreateNewVButton")
        self.gridLayout_2.addWidget(self.CreateNewVButton, 1, 1, 1, 1)
        self.pg1_settings_contras_label = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pg1_settings_contras_label.sizePolicy().hasHeightForWidth()
        )
        self.pg1_settings_contras_label.setSizePolicy(sizePolicy)
        self.pg1_settings_contras_label.setMinimumSize(QtCore.QSize(0, 0))
        self.pg1_settings_contras_label.setMaximumSize(QtCore.QSize(600, 1000))
        font = QtGui.QFont()
        font.setFamily("Lato-light")
        font.setPointSize(9)
        self.pg1_settings_contras_label.setFont(font)
        self.pg1_settings_contras_label.setStyleSheet(
            "QLabel{\n"
            '    font-family:"Lato-light";\n'
            "    font-size: 21px;\n"
            "    border: 1px solid;\n"
            "    color: rgba(60, 60, 60,255);\n"
            "    border:0px solid;\n"
            "}\n"
            ""
        )
        self.pg1_settings_contras_label.setScaledContents(False)
        self.pg1_settings_contras_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignCenter
        )
        self.pg1_settings_contras_label.setWordWrap(True)
        self.pg1_settings_contras_label.setObjectName("pg1_settings_contras_label")
        self.gridLayout_2.addWidget(self.pg1_settings_contras_label, 0, 0, 1, 2)
        self.pg1_settings_contras_label_2 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pg1_settings_contras_label_2.sizePolicy().hasHeightForWidth()
        )
        self.pg1_settings_contras_label_2.setSizePolicy(sizePolicy)
        self.pg1_settings_contras_label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pg1_settings_contras_label_2.setMaximumSize(QtCore.QSize(600, 1000))
        font = QtGui.QFont()
        font.setFamily("Lato-light")
        font.setPointSize(9)
        self.pg1_settings_contras_label_2.setFont(font)
        self.pg1_settings_contras_label_2.setStyleSheet(
            "QLabel{\n"
            '    font-family:"Lato-light";\n'
            "    font-size: 21px;\n"
            "    border: 1px solid;\n"
            "    color: rgba(110,110, 0,255);\n"
            "    border:0px solid;\n"
            "}\n"
            ""
        )
        self.pg1_settings_contras_label_2.setScaledContents(False)
        self.pg1_settings_contras_label_2.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignCenter
        )
        self.pg1_settings_contras_label_2.setWordWrap(True)
        self.pg1_settings_contras_label_2.setObjectName("pg1_settings_contras_label_2")
        self.gridLayout_2.addWidget(self.pg1_settings_contras_label_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CreateNewVButton.setText(_translate("Form", "Skip"))
        self.pg1_settings_contras_label.setText(
            _translate(
                "Form",
                "To start off your analysis let's select the region you would like to measure! If you dont want to measure a specific region thats fine, select any part for now. For this tutorial lets say you would like to measure C.elegan's head..!",
            )
        )
        self.pg1_settings_contras_label_2.setText(
            _translate("Form", "Select C.elegan's head to move on.")
        )
