# ../celer_sight_ai/UiAssets/quickToolStickAreaForm.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(94, 585)
        Form.setStyleSheet(
            "background-color: rgba(85, 255, 255,60);\n"
            "\n"
            "             border-width: 2px;  \n"
            "             border-color:  rgba(85, 255, 255,220);\n"
            "             border-style: solid;  \n"
            "             border-radius: 15;  \n"
            "             padding: 3px;  \n"
            "             font-size: 12px;  \n"
            "             padding-left: 5px;  \n"
            "             padding-right: 5px;  "
        )

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
