# ../celer_sight_ai/UiAssets/CurrentToolQuickSettings.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(260, 275)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setStyleSheet("")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolsFrame = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolsFrame.sizePolicy().hasHeightForWidth())
        self.toolsFrame.setSizePolicy(sizePolicy)
        self.toolsFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolsFrame.setStyleSheet("QFrame{\n"
"background-color: rgba(200,200,200,120);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-color:rgba(0,0,0,95);\n"
"border-radius:6px;\n"
"}\n"
"QLabel{\n"
"background-color: rgba(200,200,200,0);\n"
"border-width:0px;\n"
"border-style:solid;\n"
"border-color:rgba(0,0,0,0);\n"
"border-radius:0px;\n"
"}\n"
"        QSlider::sub-page{\n"
"         background-color:rgb(210, 210, 210);\n"
"margin-left:4px;\n"
"\n"
"        }\n"
"        QSlider::groove{\n"
"        background-color:rgb(170, 170, 170);\n"
"        border: 0px solid black;\n"
"        height: 4px;\n"
"        border-radius: 2px;\n"
"margin-left:4px;\n"
"        }\n"
"\n"
"        QSlider::handle{\n"
"        background-color: white;\n"
"        border: 0px solid black; \n"
"        width: 17px; \n"
"        height: 14px; \n"
"        line-height: 6px; \n"
"        margin-top: -6px; \n"
"        margin-bottom: -6px; \n"
"        border-radius:8px;\n"
"        \n"
"}")
        self.toolsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.toolsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.toolsFrame.setObjectName("toolsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.toolsFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.opacitySkeletonGBLabla = QtWidgets.QLabel(parent=self.toolsFrame)
        self.opacitySkeletonGBLabla.setMaximumSize(QtCore.QSize(16777215, 18))
        self.opacitySkeletonGBLabla.setObjectName("opacitySkeletonGBLabla")
        self.gridLayout.addWidget(self.opacitySkeletonGBLabla, 8, 3, 1, 1)
        self.lineWidthLabelPolygonTool = QtWidgets.QLabel(parent=self.toolsFrame)
        self.lineWidthLabelPolygonTool.setMinimumSize(QtCore.QSize(54, 0))
        self.lineWidthLabelPolygonTool.setMaximumSize(QtCore.QSize(16777215, 22))
        self.lineWidthLabelPolygonTool.setObjectName("lineWidthLabelPolygonTool")
        self.gridLayout.addWidget(self.lineWidthLabelPolygonTool, 1, 0, 1, 1)
        self.pushButtonColorBGTool = QtWidgets.QPushButton(parent=self.toolsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColorBGTool.sizePolicy().hasHeightForWidth())
        self.pushButtonColorBGTool.setSizePolicy(sizePolicy)
        self.pushButtonColorBGTool.setMaximumSize(QtCore.QSize(20, 18))
        self.pushButtonColorBGTool.setStyleSheet("background-color: rgb(0, 25, 255);")
        self.pushButtonColorBGTool.setText("")
        self.pushButtonColorBGTool.setObjectName("pushButtonColorBGTool")
        self.gridLayout.addWidget(self.pushButtonColorBGTool, 8, 2, 1, 1)
        self.horizontalSliderlineWidthPolygonTool = QtWidgets.QSlider(parent=self.toolsFrame)
        self.horizontalSliderlineWidthPolygonTool.setMaximumSize(QtCore.QSize(60, 20))
        self.horizontalSliderlineWidthPolygonTool.setMinimum(1)
        self.horizontalSliderlineWidthPolygonTool.setMaximum(20)
        self.horizontalSliderlineWidthPolygonTool.setPageStep(2)
        self.horizontalSliderlineWidthPolygonTool.setProperty("value", 2)
        self.horizontalSliderlineWidthPolygonTool.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSliderlineWidthPolygonTool.setObjectName("horizontalSliderlineWidthPolygonTool")
        self.gridLayout.addWidget(self.horizontalSliderlineWidthPolygonTool, 1, 2, 1, 2)
        self.spinBoxradiusSkeletonGB = QtWidgets.QSpinBox(parent=self.toolsFrame)
        self.spinBoxradiusSkeletonGB.setMaximumSize(QtCore.QSize(16777215, 18))
        self.spinBoxradiusSkeletonGB.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBoxradiusSkeletonGB.setMaximum(400)
        self.spinBoxradiusSkeletonGB.setProperty("value", 75)
        self.spinBoxradiusSkeletonGB.setObjectName("spinBoxradiusSkeletonGB")
        self.gridLayout.addWidget(self.spinBoxradiusSkeletonGB, 5, 4, 1, 1)
        self.horizontalSliderPolygonTool = QtWidgets.QSlider(parent=self.toolsFrame)
        self.horizontalSliderPolygonTool.setMaximumSize(QtCore.QSize(60, 18))
        self.horizontalSliderPolygonTool.setMinimum(1)
        self.horizontalSliderPolygonTool.setMaximum(100)
        self.horizontalSliderPolygonTool.setProperty("value", 5)
        self.horizontalSliderPolygonTool.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSliderPolygonTool.setObjectName("horizontalSliderPolygonTool")
        self.gridLayout.addWidget(self.horizontalSliderPolygonTool, 0, 2, 1, 2)
        self.spinBoxPolygonTool = QtWidgets.QSpinBox(parent=self.toolsFrame)
        self.spinBoxPolygonTool.setMaximumSize(QtCore.QSize(16777215, 18))
        self.spinBoxPolygonTool.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBoxPolygonTool.setMinimum(1)
        self.spinBoxPolygonTool.setMaximum(102)
        self.spinBoxPolygonTool.setProperty("value", 5)
        self.spinBoxPolygonTool.setObjectName("spinBoxPolygonTool")
        self.gridLayout.addWidget(self.spinBoxPolygonTool, 0, 4, 1, 1)
        self.colorPolygonTool = QtWidgets.QLabel(parent=self.toolsFrame)
        self.colorPolygonTool.setMaximumSize(QtCore.QSize(16777215, 18))
        self.colorPolygonTool.setObjectName("colorPolygonTool")
        self.gridLayout.addWidget(self.colorPolygonTool, 10, 0, 1, 1)
        self.brushSizeSliderGrubCut = QtWidgets.QSlider(parent=self.toolsFrame)
        self.brushSizeSliderGrubCut.setMaximumSize(QtCore.QSize(60, 18))
        self.brushSizeSliderGrubCut.setMaximum(200)
        self.brushSizeSliderGrubCut.setProperty("value", 40)
        self.brushSizeSliderGrubCut.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.brushSizeSliderGrubCut.setObjectName("brushSizeSliderGrubCut")
        self.gridLayout.addWidget(self.brushSizeSliderGrubCut, 6, 2, 1, 2)
        self.brushSizeGrubCut = QtWidgets.QLabel(parent=self.toolsFrame)
        self.brushSizeGrubCut.setMaximumSize(QtCore.QSize(16777215, 26))
        self.brushSizeGrubCut.setObjectName("brushSizeGrubCut")
        self.gridLayout.addWidget(self.brushSizeGrubCut, 6, 0, 1, 1)
        self.horizontalSliderSkeletonGBTool = QtWidgets.QSlider(parent=self.toolsFrame)
        self.horizontalSliderSkeletonGBTool.setMaximumSize(QtCore.QSize(60, 18))
        self.horizontalSliderSkeletonGBTool.setMaximum(400)
        self.horizontalSliderSkeletonGBTool.setProperty("value", 75)
        self.horizontalSliderSkeletonGBTool.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSliderSkeletonGBTool.setObjectName("horizontalSliderSkeletonGBTool")
        self.gridLayout.addWidget(self.horizontalSliderSkeletonGBTool, 5, 2, 1, 2)
        self.radiuslabelPolygon = QtWidgets.QLabel(parent=self.toolsFrame)
        self.radiuslabelPolygon.setMinimumSize(QtCore.QSize(41, 0))
        self.radiuslabelPolygon.setMaximumSize(QtCore.QSize(16777215, 18))
        self.radiuslabelPolygon.setObjectName("radiuslabelPolygon")
        self.gridLayout.addWidget(self.radiuslabelPolygon, 0, 0, 1, 1)
        self.opacityPolygonLabla = QtWidgets.QLabel(parent=self.toolsFrame)
        self.opacityPolygonLabla.setMaximumSize(QtCore.QSize(16777215, 18))
        self.opacityPolygonLabla.setObjectName("opacityPolygonLabla")
        self.gridLayout.addWidget(self.opacityPolygonLabla, 10, 3, 1, 1)
        self.brushSizeSpinBoxGrabCut = QtWidgets.QSpinBox(parent=self.toolsFrame)
        self.brushSizeSpinBoxGrabCut.setMaximumSize(QtCore.QSize(16777215, 18))
        self.brushSizeSpinBoxGrabCut.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.brushSizeSpinBoxGrabCut.setMaximum(200)
        self.brushSizeSpinBoxGrabCut.setProperty("value", 40)
        self.brushSizeSpinBoxGrabCut.setObjectName("brushSizeSpinBoxGrabCut")
        self.gridLayout.addWidget(self.brushSizeSpinBoxGrabCut, 6, 4, 1, 1)
        self.lineWidthSpinBoxPolygonTool = QtWidgets.QSpinBox(parent=self.toolsFrame)
        self.lineWidthSpinBoxPolygonTool.setMaximumSize(QtCore.QSize(16777215, 18))
        self.lineWidthSpinBoxPolygonTool.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.lineWidthSpinBoxPolygonTool.setMinimum(1)
        self.lineWidthSpinBoxPolygonTool.setMaximum(20)
        self.lineWidthSpinBoxPolygonTool.setProperty("value", 2)
        self.lineWidthSpinBoxPolygonTool.setObjectName("lineWidthSpinBoxPolygonTool")
        self.gridLayout.addWidget(self.lineWidthSpinBoxPolygonTool, 1, 4, 1, 1)
        self.spinBoxOpacityPolygon = QtWidgets.QSpinBox(parent=self.toolsFrame)
        self.spinBoxOpacityPolygon.setMaximumSize(QtCore.QSize(16777215, 18))
        self.spinBoxOpacityPolygon.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBoxOpacityPolygon.setObjectName("spinBoxOpacityPolygon")
        self.gridLayout.addWidget(self.spinBoxOpacityPolygon, 10, 4, 1, 1)
        self.RadiusSkeletonGB = QtWidgets.QLabel(parent=self.toolsFrame)
        self.RadiusSkeletonGB.setMaximumSize(QtCore.QSize(16777215, 18))
        self.RadiusSkeletonGB.setObjectName("RadiusSkeletonGB")
        self.gridLayout.addWidget(self.RadiusSkeletonGB, 5, 0, 1, 1)
        self.colorSkeletonGB = QtWidgets.QLabel(parent=self.toolsFrame)
        self.colorSkeletonGB.setMaximumSize(QtCore.QSize(16777215, 18))
        self.colorSkeletonGB.setObjectName("colorSkeletonGB")
        self.gridLayout.addWidget(self.colorSkeletonGB, 8, 0, 1, 1)
        self.pushButtonColorPolygonTool = QtWidgets.QPushButton(parent=self.toolsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonColorPolygonTool.sizePolicy().hasHeightForWidth())
        self.pushButtonColorPolygonTool.setSizePolicy(sizePolicy)
        self.pushButtonColorPolygonTool.setMaximumSize(QtCore.QSize(20, 18))
        self.pushButtonColorPolygonTool.setStyleSheet("background-color: rgb(17, 0, 255);")
        self.pushButtonColorPolygonTool.setText("")
        self.pushButtonColorPolygonTool.setObjectName("pushButtonColorPolygonTool")
        self.gridLayout.addWidget(self.pushButtonColorPolygonTool, 10, 2, 1, 1)
        self.spinBoxOpacitySkeletonGB = QtWidgets.QSpinBox(parent=self.toolsFrame)
        self.spinBoxOpacitySkeletonGB.setMaximumSize(QtCore.QSize(16777215, 18))
        self.spinBoxOpacitySkeletonGB.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBoxOpacitySkeletonGB.setMinimum(1)
        self.spinBoxOpacitySkeletonGB.setMaximum(255)
        self.spinBoxOpacitySkeletonGB.setProperty("value", 100)
        self.spinBoxOpacitySkeletonGB.setObjectName("spinBoxOpacitySkeletonGB")
        self.gridLayout.addWidget(self.spinBoxOpacitySkeletonGB, 8, 4, 1, 1)
        self.gridLayout_3.addWidget(self.toolsFrame, 3, 0, 1, 1)
        self.VideoFramePlace = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoFramePlace.sizePolicy().hasHeightForWidth())
        self.VideoFramePlace.setSizePolicy(sizePolicy)
        self.VideoFramePlace.setMinimumSize(QtCore.QSize(50, 50))
        self.VideoFramePlace.setMaximumSize(QtCore.QSize(16777215, 50))
        self.VideoFramePlace.setBaseSize(QtCore.QSize(0, 0))
        self.VideoFramePlace.setStyleSheet("\n"
"QFrame{\n"
"    background-color:rgba(75,75,75);\n"
"    border:1px solid;\n"
"border-radius:10px;\n"
"border-color:rgba(25,25,25,200);\n"
"    }\n"
"\n"
"")
        self.VideoFramePlace.setObjectName("VideoFramePlace")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.VideoFramePlace)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3.addWidget(self.VideoFramePlace, 1, 0, 1, 1)
        self.annotation_tool_frame = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.annotation_tool_frame.sizePolicy().hasHeightForWidth())
        self.annotation_tool_frame.setSizePolicy(sizePolicy)
        self.annotation_tool_frame.setMinimumSize(QtCore.QSize(150, 65))
        self.annotation_tool_frame.setMaximumSize(QtCore.QSize(150, 65))
        self.annotation_tool_frame.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.annotation_tool_frame.setStyleSheet("QFrame{\n"
"background-color: rgba(200,200,200,170);\n"
"border-width:1px;\n"
"border-style:solid;\n"
"border-color:rgba(96,96,96);\n"
"padding:5px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:4px;\n"
"padding: 0 px;\n"
"margin: 2px;\n"
"\n"
"}\n"
"")
        self.annotation_tool_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.annotation_tool_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.annotation_tool_frame.setObjectName("annotation_tool_frame")
        self.annotation_tool_frame_gridLayout = QtWidgets.QGridLayout(self.annotation_tool_frame)
        self.annotation_tool_frame_gridLayout.setContentsMargins(3, 4, 3, 4)
        self.annotation_tool_frame_gridLayout.setObjectName("annotation_tool_frame_gridLayout")
        self.pushButtonQuickToolsAutoSpline = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickToolsAutoSpline.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickToolsAutoSpline.setSizePolicy(sizePolicy)
        self.pushButtonQuickToolsAutoSpline.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsAutoSpline.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsAutoSpline.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickToolsAutoSpline.setStyleSheet("\n"
"background-color:rgb(45,45,45);")
        self.pushButtonQuickToolsAutoSpline.setText("")
        self.pushButtonQuickToolsAutoSpline.setObjectName("pushButtonQuickToolsAutoSpline")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickToolsAutoSpline, 1, 3, 1, 1)
        self.pushButtonQuickToolsMoveMagicBrush = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickToolsMoveMagicBrush.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickToolsMoveMagicBrush.setSizePolicy(sizePolicy)
        self.pushButtonQuickToolsMoveMagicBrush.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsMoveMagicBrush.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsMoveMagicBrush.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickToolsMoveMagicBrush.setStyleSheet("\n"
"background-color:rgb(45,45,45);")
        self.pushButtonQuickToolsMoveMagicBrush.setText("")
        self.pushButtonQuickToolsMoveMagicBrush.setObjectName("pushButtonQuickToolsMoveMagicBrush")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickToolsMoveMagicBrush, 0, 3, 1, 1)
        self.pushButtonQuickToolsErraseTool = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickToolsErraseTool.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickToolsErraseTool.setSizePolicy(sizePolicy)
        self.pushButtonQuickToolsErraseTool.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsErraseTool.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsErraseTool.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickToolsErraseTool.setStyleSheet("\n"
"background-color:rgb(45,45,45);")
        self.pushButtonQuickToolsErraseTool.setText("")
        self.pushButtonQuickToolsErraseTool.setObjectName("pushButtonQuickToolsErraseTool")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickToolsErraseTool, 0, 2, 1, 1)
        self.pushButtonQuickToolsRemoveSelectionTool = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickToolsRemoveSelectionTool.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickToolsRemoveSelectionTool.setSizePolicy(sizePolicy)
        self.pushButtonQuickToolsRemoveSelectionTool.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsRemoveSelectionTool.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsRemoveSelectionTool.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickToolsRemoveSelectionTool.setStyleSheet("\n"
"background-color:rgb(45,45,45);")
        self.pushButtonQuickToolsRemoveSelectionTool.setText("")
        self.pushButtonQuickToolsRemoveSelectionTool.setObjectName("pushButtonQuickToolsRemoveSelectionTool")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickToolsRemoveSelectionTool, 1, 4, 1, 1)
        self.pushButtonQuickToolsAutoRF_MODE = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickToolsAutoRF_MODE.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickToolsAutoRF_MODE.setSizePolicy(sizePolicy)
        self.pushButtonQuickToolsAutoRF_MODE.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsAutoRF_MODE.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsAutoRF_MODE.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickToolsAutoRF_MODE.setStyleSheet("\n"
"background-color:rgb(45,45,45);")
        self.pushButtonQuickToolsAutoRF_MODE.setText("")
        self.pushButtonQuickToolsAutoRF_MODE.setObjectName("pushButtonQuickToolsAutoRF_MODE")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickToolsAutoRF_MODE, 0, 4, 1, 1)
        self.pushButtonQuickToolsSelectionTool = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickToolsSelectionTool.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickToolsSelectionTool.setSizePolicy(sizePolicy)
        self.pushButtonQuickToolsSelectionTool.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsSelectionTool.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsSelectionTool.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickToolsSelectionTool.setStyleSheet("\n"
"background-color:rgb(45,45,45);")
        self.pushButtonQuickToolsSelectionTool.setText("")
        self.pushButtonQuickToolsSelectionTool.setObjectName("pushButtonQuickToolsSelectionTool")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickToolsSelectionTool, 0, 1, 1, 1)
        self.pushButtonQuickToolsPolygonTool = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickToolsPolygonTool.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickToolsPolygonTool.setSizePolicy(sizePolicy)
        self.pushButtonQuickToolsPolygonTool.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsPolygonTool.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsPolygonTool.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickToolsPolygonTool.setStyleSheet("\n"
"background-color:rgb(45,45,45);")
        self.pushButtonQuickToolsPolygonTool.setText("")
        self.pushButtonQuickToolsPolygonTool.setObjectName("pushButtonQuickToolsPolygonTool")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickToolsPolygonTool, 1, 1, 1, 1)
        self.pushButtonQuickToolsAutoToolBox = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickToolsAutoToolBox.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickToolsAutoToolBox.setSizePolicy(sizePolicy)
        self.pushButtonQuickToolsAutoToolBox.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsAutoToolBox.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsAutoToolBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickToolsAutoToolBox.setStyleSheet("\n"
"background-color:rgb(45,45,45);")
        self.pushButtonQuickToolsAutoToolBox.setText("")
        self.pushButtonQuickToolsAutoToolBox.setObjectName("pushButtonQuickToolsAutoToolBox")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickToolsAutoToolBox, 1, 2, 1, 1)
        self.pushButtonQuickTools_BrushMask = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickTools_BrushMask.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickTools_BrushMask.setSizePolicy(sizePolicy)
        self.pushButtonQuickTools_BrushMask.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickTools_BrushMask.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickTools_BrushMask.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickTools_BrushMask.setStyleSheet("\n"
"background-color:rgb(45,45,45);\n"
"")
        self.pushButtonQuickTools_BrushMask.setText("")
        self.pushButtonQuickTools_BrushMask.setObjectName("pushButtonQuickTools_BrushMask")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickTools_BrushMask, 0, 0, 1, 1)
        self.pushButtonQuickToolsKeypoint = QtWidgets.QPushButton(parent=self.annotation_tool_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuickToolsKeypoint.sizePolicy().hasHeightForWidth())
        self.pushButtonQuickToolsKeypoint.setSizePolicy(sizePolicy)
        self.pushButtonQuickToolsKeypoint.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsKeypoint.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonQuickToolsKeypoint.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonQuickToolsKeypoint.setStyleSheet("\n"
"background-color:rgb(45,45,45);")
        self.pushButtonQuickToolsKeypoint.setText("")
        self.pushButtonQuickToolsKeypoint.setObjectName("pushButtonQuickToolsKeypoint")
        self.annotation_tool_frame_gridLayout.addWidget(self.pushButtonQuickToolsKeypoint, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.annotation_tool_frame, 2, 0, 1, 1)
        self.RandomForestCellModeFrame = QtWidgets.QFrame(parent=Form)
        self.RandomForestCellModeFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.RandomForestCellModeFrame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.RandomForestCellModeFrame.setStyleSheet("        QSlider::sub-page{\n"
"         background-color:rgb(210, 210, 210);\n"
"margin-left:4px;\n"
"\n"
"        }\n"
"        QSlider::groove{\n"
"        background-color:rgb(170, 170, 170);\n"
"        border: 0px solid black;\n"
"        height: 4px;\n"
"        border-radius: 2px;\n"
"margin-left:4px;\n"
"        }\n"
"\n"
"        QSlider::handle{\n"
"        background-color: white;\n"
"        border: 0px solid black; \n"
"        width: 17px; \n"
"        height: 14px; \n"
"        line-height: 6px; \n"
"        margin-top: -6px; \n"
"        margin-bottom: -6px; \n"
"        border-radius:8px;\n"
"        \n"
"}")
        self.RandomForestCellModeFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RandomForestCellModeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RandomForestCellModeFrame.setObjectName("RandomForestCellModeFrame")
        self.CellRandomForestGridLayout = QtWidgets.QGridLayout(self.RandomForestCellModeFrame)
        self.CellRandomForestGridLayout.setContentsMargins(2, 0, 2, 6)
        self.CellRandomForestGridLayout.setObjectName("CellRandomForestGridLayout")
        self.BrushRadiusCellRandomForestSlider = QtWidgets.QSlider(parent=self.RandomForestCellModeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BrushRadiusCellRandomForestSlider.sizePolicy().hasHeightForWidth())
        self.BrushRadiusCellRandomForestSlider.setSizePolicy(sizePolicy)
        self.BrushRadiusCellRandomForestSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.BrushRadiusCellRandomForestSlider.setObjectName("BrushRadiusCellRandomForestSlider")
        self.CellRandomForestGridLayout.addWidget(self.BrushRadiusCellRandomForestSlider, 13, 0, 1, 2)
        self.BrushRadiusCellRandomForestLabel = QtWidgets.QLabel(parent=self.RandomForestCellModeFrame)
        self.BrushRadiusCellRandomForestLabel.setMaximumSize(QtCore.QSize(16777215, 27))
        self.BrushRadiusCellRandomForestLabel.setStyleSheet("color:white;")
        self.BrushRadiusCellRandomForestLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BrushRadiusCellRandomForestLabel.setObjectName("BrushRadiusCellRandomForestLabel")
        self.CellRandomForestGridLayout.addWidget(self.BrushRadiusCellRandomForestLabel, 9, 0, 1, 2)
        self.BackgroundMarkerButtonTool = QtWidgets.QToolButton(parent=self.RandomForestCellModeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackgroundMarkerButtonTool.sizePolicy().hasHeightForWidth())
        self.BackgroundMarkerButtonTool.setSizePolicy(sizePolicy)
        self.BackgroundMarkerButtonTool.setMinimumSize(QtCore.QSize(30, 30))
        self.BackgroundMarkerButtonTool.setMaximumSize(QtCore.QSize(10000, 30))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BackgroundMarkerButtonTool.setFont(font)
        self.BackgroundMarkerButtonTool.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.BackgroundMarkerButtonTool.setStyleSheet("QToolButton{\n"
"color:white;\n"
"background-color: rgba(255,0,0,20);\n"
"             border-width: 1px;  \n"
"border-color: rgba(255,0,0,100);\n"
"             border-style: solid;  \n"
"             border-radius: 5;  \n"
"}\n"
"QToolButton::checked{\n"
"background-color: rgba(255,0,0,180);\n"
"             border-width: 1px;  \n"
"border-color: rgba(0,0,0,255);\n"
"             border-style: solid;  \n"
"             border-radius: 5;  \n"
"}\n"
"QToolButton:hover{\n"
"background-color: rgba(255,0,0,180);\n"
"             border-width: 1px;  \n"
"border-color: rgba(0,0,0,200);\n"
"             border-style: solid;  \n"
"             border-radius: 5;  \n"
"}\n"
"QToolButton:hover:checked{\n"
"background-color: rgba(255,0,0,220);\n"
"             border-width: 1px;  \n"
"border-color: rgba(0,0,0,100);\n"
"             border-style: solid;  \n"
"             border-radius: 5;  \n"
"}")
        self.BackgroundMarkerButtonTool.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(" UiAssets/../data/icons/paintbrush_ml.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.BackgroundMarkerButtonTool.setIcon(icon)
        self.BackgroundMarkerButtonTool.setCheckable(True)
        self.BackgroundMarkerButtonTool.setAutoExclusive(True)
        self.BackgroundMarkerButtonTool.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.BackgroundMarkerButtonTool.setObjectName("BackgroundMarkerButtonTool")
        self.CellRandomForestGridLayout.addWidget(self.BackgroundMarkerButtonTool, 4, 0, 1, 2)
        self.clearMarksrsCELLbtn = QtWidgets.QToolButton(parent=self.RandomForestCellModeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearMarksrsCELLbtn.sizePolicy().hasHeightForWidth())
        self.clearMarksrsCELLbtn.setSizePolicy(sizePolicy)
        self.clearMarksrsCELLbtn.setMinimumSize(QtCore.QSize(0, 29))
        self.clearMarksrsCELLbtn.setMaximumSize(QtCore.QSize(1000, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.clearMarksrsCELLbtn.setFont(font)
        self.clearMarksrsCELLbtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.clearMarksrsCELLbtn.setStyleSheet("QToolButton{\n"
"border-color: rgb(115,0,0);\n"
"border-width:2px;\n"
"background-color:rgb(60,10,10);\n"
"color:white;\n"
"font: bold;\n"
"font-size: 13px;\n"
"border-radius:5px;\n"
"padding-right:3px;\n"
"padding-left:5px;\n"
"\n"
"}\n"
"QToolButton:hover{\n"
"border-color: rgb(255,0,0);\n"
"background-color:rgb(60,10,10);\n"
"color:white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(" UiAssets/../data/icons/delete_smooth_red.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.clearMarksrsCELLbtn.setIcon(icon1)
        self.clearMarksrsCELLbtn.setIconSize(QtCore.QSize(14, 16))
        self.clearMarksrsCELLbtn.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.clearMarksrsCELLbtn.setObjectName("clearMarksrsCELLbtn")
        self.CellRandomForestGridLayout.addWidget(self.clearMarksrsCELLbtn, 15, 0, 1, 2)
        self.ApplyAndDoneBtnRandomForestMode = QtWidgets.QToolButton(parent=self.RandomForestCellModeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ApplyAndDoneBtnRandomForestMode.sizePolicy().hasHeightForWidth())
        self.ApplyAndDoneBtnRandomForestMode.setSizePolicy(sizePolicy)
        self.ApplyAndDoneBtnRandomForestMode.setMinimumSize(QtCore.QSize(0, 31))
        self.ApplyAndDoneBtnRandomForestMode.setMaximumSize(QtCore.QSize(1000, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ApplyAndDoneBtnRandomForestMode.setFont(font)
        self.ApplyAndDoneBtnRandomForestMode.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ApplyAndDoneBtnRandomForestMode.setStyleSheet("QToolButton{\n"
"border-color: rgb(0,115,0);\n"
"border-width:2px;\n"
"background-color:rgb(10,60,10);\n"
"color:white;\n"
"font: bold;\n"
"font-size: 13px;\n"
"border-radius:5px;\n"
"padding-right:3px;\n"
"padding-left:5px;\n"
"\n"
"}\n"
"QToolButton:hover{\n"
"border-color: rgb(0,255,0);\n"
"background-color:rgb(10,60,10);\n"
"color:white;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(" UiAssets/../data/icons/check_smooth_green.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.ApplyAndDoneBtnRandomForestMode.setIcon(icon2)
        self.ApplyAndDoneBtnRandomForestMode.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.ApplyAndDoneBtnRandomForestMode.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.ApplyAndDoneBtnRandomForestMode.setObjectName("ApplyAndDoneBtnRandomForestMode")
        self.CellRandomForestGridLayout.addWidget(self.ApplyAndDoneBtnRandomForestMode, 14, 0, 1, 2)
        self.CellsMarkerButtonTool = QtWidgets.QToolButton(parent=self.RandomForestCellModeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CellsMarkerButtonTool.sizePolicy().hasHeightForWidth())
        self.CellsMarkerButtonTool.setSizePolicy(sizePolicy)
        self.CellsMarkerButtonTool.setMinimumSize(QtCore.QSize(0, 30))
        self.CellsMarkerButtonTool.setMaximumSize(QtCore.QSize(10000, 30))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CellsMarkerButtonTool.setFont(font)
        self.CellsMarkerButtonTool.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CellsMarkerButtonTool.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.CellsMarkerButtonTool.setStyleSheet("QToolButton{\n"
"background-color: rgba(0,255,0,20);\n"
"             border-width: 1px;  \n"
"border-color: rgba(0,255,0,100);\n"
"             border-style: solid;  \n"
"             border-radius: 5;  \n"
"    color:white;\n"
"}\n"
"QToolButton::checked{\n"
"background-color: rgba(0,255,0,180);\n"
"             border-width: 1px;  \n"
"border-color: rgba(0,0,0,255);\n"
"             border-style: solid;  \n"
"             border-radius: 5;  \n"
"}\n"
"QToolButton:hover{\n"
"background-color: rgba(0,255,0,180);\n"
"             border-width: 1px;  \n"
"border-color: rgba(0,0,0,200);\n"
"             border-style: solid;  \n"
"             border-radius: 5;  \n"
"}\n"
"QToolButton:hover:checked{\n"
"background-color: rgba(0,255,0,220);\n"
"             border-width: 1px;  \n"
"border-color: rgba(0,0,0,100);\n"
"             border-style: solid;  \n"
"             border-radius: 5;  \n"
"}")
        self.CellsMarkerButtonTool.setIcon(icon)
        self.CellsMarkerButtonTool.setIconSize(QtCore.QSize(16, 16))
        self.CellsMarkerButtonTool.setCheckable(True)
        self.CellsMarkerButtonTool.setAutoExclusive(True)
        self.CellsMarkerButtonTool.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.CellsMarkerButtonTool.setObjectName("CellsMarkerButtonTool")
        self.CellRandomForestGridLayout.addWidget(self.CellsMarkerButtonTool, 3, 0, 1, 2)
        self.gridLayout_3.addWidget(self.RandomForestCellModeFrame, 2, 1, 2, 1)

        self.retranslateUi(Form)
        self.horizontalSliderPolygonTool.sliderMoved['int'].connect(self.spinBoxPolygonTool.setValue) # type: ignore
        self.horizontalSliderSkeletonGBTool.sliderMoved['int'].connect(self.spinBoxradiusSkeletonGB.setValue) # type: ignore
        self.brushSizeSliderGrubCut.valueChanged['int'].connect(self.brushSizeSpinBoxGrabCut.setValue) # type: ignore
        self.spinBoxPolygonTool.valueChanged['int'].connect(self.horizontalSliderPolygonTool.setValue) # type: ignore
        self.spinBoxradiusSkeletonGB.valueChanged['int'].connect(self.horizontalSliderSkeletonGBTool.setValue) # type: ignore
        self.brushSizeSpinBoxGrabCut.valueChanged['int'].connect(self.brushSizeSliderGrubCut.setValue) # type: ignore
        self.horizontalSliderlineWidthPolygonTool.sliderMoved['int'].connect(self.lineWidthSpinBoxPolygonTool.setValue) # type: ignore
        self.lineWidthSpinBoxPolygonTool.valueChanged['int'].connect(self.horizontalSliderlineWidthPolygonTool.setValue) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.horizontalSliderSkeletonGBTool, self.brushSizeSliderGrubCut)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.opacitySkeletonGBLabla.setText(_translate("Form", "Opcaity"))
        self.lineWidthLabelPolygonTool.setText(_translate("Form", "Line\n"
"Width"))
        self.colorPolygonTool.setText(_translate("Form", "Color"))
        self.brushSizeGrubCut.setText(_translate("Form", "Brush\n"
"Size"))
        self.radiuslabelPolygon.setText(_translate("Form", "Radius"))
        self.opacityPolygonLabla.setText(_translate("Form", "Opacity"))
        self.RadiusSkeletonGB.setText(_translate("Form", "Radius"))
        self.colorSkeletonGB.setText(_translate("Form", "Color"))
        self.BrushRadiusCellRandomForestLabel.setText(_translate("Form", "Radius"))
        self.BackgroundMarkerButtonTool.setText(_translate("Form", "Background"))
        self.clearMarksrsCELLbtn.setText(_translate("Form", "Cancel"))
        self.ApplyAndDoneBtnRandomForestMode.setText(_translate("Form", "Accept"))
        self.CellsMarkerButtonTool.setText(_translate("Form", "Subgect"))
