# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\manos\Documents\topfluov3\UiAssets\testDragableButton.ui'
#
# Created by: PyQt6 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1160, 674)
        Dialog.setStyleSheet(
            "        QToolTip  \n"
            "         {  \n"
            "              border: 1px solid black;  \n"
            "              background-color: #ffa02f;  \n"
            "              padding: 1px;  \n"
            "              border-radius: 3px;  \n"
            "              opacity: 100;  \n"
            "         }  \n"
            "           \n"
            "         QWidget  \n"
            "         {  \n"
            "             color: #b1b1b1;  \n"
            "             background-color: #323232;  \n"
            "         }  \n"
            "           \n"
            "         QWidget:item:hover  \n"
            "         {  \n"
            "             background-color:QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "             color: #000000;  \n"
            "         }  \n"
            "           \n"
            "         QWidget:item:selected  \n"
            "         {  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "         }  \n"
            "           \n"
            "         QMenuBar::item  \n"
            "         {  \n"
            "             background: transparent;  \n"
            "         }  \n"
            "           \n"
            "         QMenuBar::item:selected  \n"
            "         {  \n"
            "             background: transparent;  \n"
            "             border: 1px solid #ffaa00;  \n"
            "         }  \n"
            "           \n"
            "         QMenuBar::item:pressed  \n"
            "         {  \n"
            "             background: #444;  \n"
            "             border: 1px solid #000;  \n"
            "             background-color: QLinearGradient(  \n"
            "                 x1:0, y1:0,  \n"
            "                 x2:0, y2:1,  \n"
            "                 stop:1 #212121,  \n"
            "                 stop:0.4 #343434/*,  \n"
            "                 stop:0.2 #343434,  \n"
            "                 stop:0.1 #ffaa00*/  \n"
            "             );  \n"
            "             margin-bottom:-1px;  \n"
            "             padding-bottom:1px;  \n"
            "         }  \n"
            "           \n"
            "         QMenu  \n"
            "         {  \n"
            "             border: 1px solid #000;  \n"
            "         }  \n"
            "           \n"
            "         QMenu::item  \n"
            "         {  \n"
            "             padding: 2px 20px 2px 20px;  \n"
            "         }  \n"
            "           \n"
            "         QMenu::item:selected  \n"
            "         {  \n"
            "             color: #000000;  \n"
            "         }  \n"
            "           \n"
            "         QWidget:disabled  \n"
            "         {  \n"
            "             color: #404040;  \n"
            "             background-color: #323232;  \n"
            "         }  \n"
            "           \n"
            "         QAbstractItemView  \n"
            "         {  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);  \n"
            "         }  \n"
            "           \n"
            "         QWidget:focus  \n"
            "         {  \n"
            "             /*border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/  \n"
            "         }  \n"
            "           \n"
            "         QLineEdit  \n"
            "         {  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);  \n"
            "             padding: 1px;  \n"
            "             border-style: solid;  \n"
            "             border: 1px solid #1e1e1e;  \n"
            "             border-radius: 5;  \n"
            "         }  \n"
            "           \n"
            "         QPushButton  \n"
            "         {  \n"
            "             color: #b1b1b1;  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);  \n"
            "             border-width: 1px;  \n"
            "             border-color: #1e1e1e;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 6;  \n"
            "             padding: 3px;  \n"
            "             font-size: 12px;  \n"
            "             padding-left: 5px;  \n"
            "             padding-right: 5px;  \n"
            "         }  \n"
            "           \n"
            "         QPushButton:pressed  \n"
            "         {  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);  \n"
            "         }  \n"
            "           \n"
            "         QComboBox  \n"
            "         {  \n"
            "             selection-background-color: #ffaa00;  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);  \n"
            "             border-style: solid;  \n"
            "             border: 1px solid #1e1e1e;  \n"
            "             border-radius: 5;  \n"
            "         }  \n"
            "           \n"
            "         QComboBox:hover,QPushButton:hover  \n"
            "         {  \n"
            "             border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "         }  \n"
            "           \n"
            "           \n"
            "         QComboBox:on  \n"
            "         {  \n"
            "             padding-top: 3px;  \n"
            "             padding-left: 4px;  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);  \n"
            "             selection-background-color: #ffaa00;  \n"
            "         }  \n"
            "           \n"
            "         QComboBox QAbstractItemView  \n"
            "         {  \n"
            "             border: 2px solid darkgray;  \n"
            "             selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "         }  \n"
            "           \n"
            "         QComboBox::drop-down  \n"
            "         {  \n"
            "              subcontrol-origin: padding;  \n"
            "              subcontrol-position: top right;  \n"
            "              width: 15px;  \n"
            "           \n"
            "              border-left-width: 0px;  \n"
            "              border-left-color: darkgray;  \n"
            "              border-left-style: solid; /* just a single line */  \n"
            "              border-top-right-radius: 3px; /* same radius as the QComboBox */  \n"
            "              border-bottom-right-radius: 3px;  \n"
            "          }  \n"
            "           \n"
            "         QComboBox::down-arrow  \n"
            "         {  \n"
            "              image: url(:/down_arrow.png);  \n"
            "         }  \n"
            "           \n"
            "         QGroupBox:focus  \n"
            "         {  \n"
            "         border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "         }  \n"
            "           \n"
            "         QTextEdit:focus  \n"
            "         {  \n"
            "             border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar:horizontal {  \n"
            "              border: 1px solid #222222;  \n"
            "              background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);  \n"
            "              height: 7px;  \n"
            "              margin: 0px 16px 0 16px;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::handle:horizontal  \n"
            "         {  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);  \n"
            "               min-height: 20px;  \n"
            "               border-radius: 2px;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::add-line:horizontal {  \n"
            "               border: 1px solid #1b1b19;  \n"
            "               border-radius: 2px;  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "               width: 14px;  \n"
            "               subcontrol-position: right;  \n"
            "               subcontrol-origin: margin;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::sub-line:horizontal {  \n"
            "               border: 1px solid #1b1b19;  \n"
            "               border-radius: 2px;  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "               width: 14px;  \n"
            "              subcontrol-position: left;  \n"
            "              subcontrol-origin: margin;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal  \n"
            "         {  \n"
            "               border: 1px solid black;  \n"
            "               width: 1px;  \n"
            "               height: 1px;  \n"
            "               background: white;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal  \n"
            "         {  \n"
            "               background: none;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar:vertical  \n"
            "         {  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);  \n"
            "               width: 7px;  \n"
            "               margin: 16px 0 16px 0;  \n"
            "               border: 1px solid #222222;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::handle:vertical  \n"
            "         {  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);  \n"
            "               min-height: 20px;  \n"
            "               border-radius: 2px;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::add-line:vertical  \n"
            "         {  \n"
            "               border: 1px solid #1b1b19;  \n"
            "               border-radius: 2px;  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "               height: 14px;  \n"
            "               subcontrol-position: bottom;  \n"
            "               subcontrol-origin: margin;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::sub-line:vertical  \n"
            "         {  \n"
            "               border: 1px solid #1b1b19;  \n"
            "               border-radius: 2px;  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);  \n"
            "               height: 14px;  \n"
            "               subcontrol-position: top;  \n"
            "               subcontrol-origin: margin;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical  \n"
            "         {  \n"
            "               border: 1px solid black;  \n"
            "               width: 1px;  \n"
            "               height: 1px;  \n"
            "               background: white;  \n"
            "         }  \n"
            "           \n"
            "           \n"
            "         QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical  \n"
            "         {  \n"
            "               background: none;  \n"
            "         }  \n"
            "           \n"
            "         QTextEdit  \n"
            "         {  \n"
            "             background-color: #242424;  \n"
            "         }  \n"
            "           \n"
            "         QPlainTextEdit  \n"
            "         {  \n"
            "             background-color: #242424;  \n"
            "         }  \n"
            "           \n"
            "         QHeaderView::section  \n"
            "         {  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);  \n"
            "             color: white;  \n"
            "             padding-left: 4px;  \n"
            "             border: 1px solid #6c6c6c;  \n"
            "         }  \n"
            "           \n"
            "         QCheckBox:disabled  \n"
            "         {  \n"
            "         color: #414141;  \n"
            "         }  \n"
            "           \n"
            "         QDockWidget::title  \n"
            "         {  \n"
            "             text-align: center;  \n"
            "             spacing: 3px; /* spacing between items in the tool bar */  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);  \n"
            "         }  \n"
            "           \n"
            "         QDockWidget::close-button, QDockWidget::float-button  \n"
            "         {  \n"
            "             text-align: center;  \n"
            "             spacing: 1px; /* spacing between items in the tool bar */  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);  \n"
            "         }  \n"
            "           \n"
            "         QDockWidget::close-button:hover, QDockWidget::float-button:hover  \n"
            "         {  \n"
            "             background: #242424;  \n"
            "         }  \n"
            "           \n"
            "         QDockWidget::close-button:pressed, QDockWidget::float-button:pressed  \n"
            "         {  \n"
            "             padding: 1px -1px -1px 1px;  \n"
            "         }  \n"
            "           \n"
            "         QMainWindow::separator  \n"
            "         {  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);  \n"
            "             color: white;  \n"
            "             padding-left: 4px;  \n"
            "             border: 1px solid #4c4c4c;  \n"
            "             spacing: 3px; /* spacing between items in the tool bar */  \n"
            "         }  \n"
            "           \n"
            "         QMainWindow::separator:hover  \n"
            "         {  \n"
            "           \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);  \n"
            "             color: white;  \n"
            "             padding-left: 4px;  \n"
            "             border: 1px solid #6c6c6c;  \n"
            "             spacing: 3px; /* spacing between items in the tool bar */  \n"
            "         }  \n"
            "           \n"
            "         QToolBar::handle  \n"
            "         {  \n"
            "              spacing: 3px; /* spacing between items in the tool bar */  \n"
            "              background: url(:/images/handle.png);  \n"
            "         }  \n"
            "           \n"
            "         QMenu::separator  \n"
            "         {  \n"
            "             height: 2px;  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);  \n"
            "             color: white;  \n"
            "             padding-left: 4px;  \n"
            "             margin-left: 10px;  \n"
            "             margin-right: 5px;  \n"
            "         }  \n"
            "           \n"
            "         QProgressBar  \n"
            "         {  \n"
            "             border: 2px solid grey;  \n"
            "             border-radius: 5px;  \n"
            "             text-align: center;  \n"
            "         }  \n"
            "           \n"
            "         QProgressBar::chunk  \n"
            "         {  \n"
            "             background-color: #d7801a;  \n"
            "             width: 2.15px;  \n"
            "             margin: 0.5px;  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab {  \n"
            "             color: #b1b1b1;  \n"
            "             border: 1px solid #444;  \n"
            "             border-bottom-style: none;  \n"
            "             background-color: #323232;  \n"
            "             padding-left: 10px;  \n"
            "             padding-right: 10px;  \n"
            "             padding-top: 3px;  \n"
            "             padding-bottom: 2px;  \n"
            "             margin-right: -1px;  \n"
            "         }  \n"
            "           \n"
            "         QTabWidget::pane {  \n"
            "             border: 1px solid #444;  \n"
            "             top: 1px;  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:last  \n"
            "         {  \n"
            "             margin-right: 0; /* the last selected tab has nothing to overlap with on the right */  \n"
            "             border-top-right-radius: 3px;  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:first:!selected  \n"
            "         {  \n"
            "          margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */  \n"
            "           \n"
            "           \n"
            "             border-top-left-radius: 3px;  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:!selected  \n"
            "         {  \n"
            "             color: #b1b1b1;  \n"
            "             border-bottom-style: solid;  \n"
            "             margin-top: 3px;  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #1c0009);  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:selected  \n"
            "         {  \n"
            "             border-top-left-radius: 3px;  \n"
            "             border-top-right-radius: 3px;  \n"
            "             margin-bottom: 0px;  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:!selected:hover  \n"
            "         {  \n"
            "             /*border-top: 2px solid #ffaa00;  \n"
            "             padding-bottom: 3px;*/  \n"
            "             border-top-left-radius: 3px;  \n"
            "             border-top-right-radius: 3px;  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #350012, stop:0.2 #4e001a, stop:0.1 #4e001a);  \n"
            "         }  \n"
            "           \n"
            "         QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{  \n"
            "             color: #b1b1b1;  \n"
            "             background-color: #323232;  \n"
            "             border: 1px solid #b1b1b1;  \n"
            "             border-radius: 6px;  \n"
            "         }  \n"
            "           \n"
            "         QRadioButton::indicator:checked  \n"
            "         {  \n"
            "             background-color: qradialgradient(  \n"
            "                 cx: 0.5, cy: 0.5,  \n"
            "                 fx: 0.5, fy: 0.5,  \n"
            "                 radius: 1.0,  \n"
            "                 stop: 0.25 #ffaa00,  \n"
            "                 stop: 0.3 #323232  \n"
            "             );  \n"
            "         }  \n"
            "           \n"
            "         QCheckBox::indicator{  \n"
            "             color: #b1b1b1;  \n"
            "             background-color: #323232;  \n"
            "             border: 1px solid #b1b1b1;  \n"
            "             width: 9px;  \n"
            "             height: 9px;  \n"
            "         }  \n"
            "           \n"
            "         QRadioButton::indicator  \n"
            "         {  \n"
            "             border-radius: 6px;  \n"
            "         }  \n"
            "           \n"
            "         QRadioButton::indicator:hover, QCheckBox::indicator:hover  \n"
            "         {  \n"
            "             border: 1px solid #ffaa00;  \n"
            "         }  \n"
            "           \n"
            "         QCheckBox::indicator:checked  \n"
            "         {  \n"
            "             image:url(:/images/checkbox.png);  \n"
            "         }  \n"
            "           \n"
            "         QCheckBox::indicator:disabled, QRadioButton::indicator:disabled  \n"
            "         {  \n"
            "             border: 1px solid #444;  \n"
            "         }  \n"
            "\n"
            "         QTableWidget::item {  \n"
            "              background-color: #FFFFFF  \n"
            "          }  \n"
            "\n"
            "         QTabBar::tab { height: 30px; width: 200px; }  \n"
            "          \n"
            "         QScrollBar { \n"
            "             border: rgba(255, 255, 255,0); \n"
            "         } \n"
            "\n"
            "         QGroupBox {  \n"
            "             border: rgba(255, 255, 255,0); \n"
            "         }  \n"
            "         QScrollArea { \n"
            "         border: rgba(255, 255, 255,0); \n"
            "          }  +     \n"
            "        QPushButton#Add_mask_btn{\n"
            "            background-color: #E5E5E5;\n"
            "        }\n"
            "        QPushButton#Add_mask_btn:hover{\n"
            "            border-color: #000000;\n"
            "            background-color: #CCCCCC;\n"
            "        }\n"
            "\n"
            "        QPushButton#Add_mask_btn:checked{\n"
            "            border-color: #2A828F;\n"
            "            background-color: #2A828F;\n"
            "        }\n"
            "        QPushButton#Delete_selected_btn{\n"
            "            background-color: #E5E5E5;\n"
            "        }\n"
            "        QPushButton#Delete_selected_btn:hover{\n"
            "            border-color: #000000;\n"
            "            background-color: #CCCCCC;\n"
            "        }\n"
            "\n"
            "        QDockWidget::title{\n"
            "        background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #273232, stop: 0.5 #242424, stop:1 #242424);\n"
            "        }\n"
            "        QDockWidget::close-button, QDockWidget::float-button{\n"
            "        color: #FFFFFF\n"
            "        background-color:  #273232\n"
            "        }\n"
            "        QDockWidget::close-button:hover, QDockWidget::float-button:hover{\n"
            "        color: #FFFFFF\n"
            "        background-color:  #273232   \n"
            "        }\n"
            "\n"
            "        QSlider::groove{\n"
            "        background-color: white\n"
            "        border: 0px solid black\n"
            "        height: 5px\n"
            "        border-radius: 1px\n"
            "        }\n"
            "\n"
            "        QSlider::handle{\n"
            "        background-color: white;\n"
            "        border: 2px solid black; \n"
            "        width: 16px; \n"
            "        height: 20px; \n"
            "        line-height: 20px; \n"
            "        margin-top: -10px; \n"
            "        margin-bottom: -10px; \n"
            "        border-radius: 10px;\n"
            "        \n"
            "        }\n"
            "        QGroupBox {\n"
            "            border: 1px solid;\n"
            "            border-color: rgb(20, 20, 20);\n"
            "            margin-top: 20px;\n"
            "            border-top-left-radius: 15px;\n"
            "            border-top-right-radius:15px;\n"
            "            border-bottom-left-radius: 15px;\n"
            "            border-bottom-right-radius: 15px;\n"
            "            background-color: rgb(90, 90, 90);\n"
            "        }\n"
            "        QGroupBox::title {\n"
            "            font-size: 12px;\n"
            "            border-top-color: rgb(255, 255, 255);\n"
            "            subcontrol-origin: margin;\n"
            "            subcontrol-position: top left;\n"
            "            border-top-left-radius: 15px;\n"
            "            border-top-right-radius:15px;\n"
            "            padding: 2px 10px;\n"
            "            background-color: rgba(255, 255, 255,0);\n"
            "            color:rgba(255, 255, 255,220);\n"
            "        }\n"
            "\n"
            "\n"
            "        QGroupBox::indicator{\n"
            "        background-color: rgba(0, 170, 127,0);\n"
            "        color: rgba(85, 255, 0,0);\n"
            "        }\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "        "
        )
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            20,
            6,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet(
            "background-color: rgb(220,220, 220);\n" "border-radius: 8;"
        )
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(200, 50))
        self.frame_4.setBaseSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet(
            "background-color: rgba(21, 21, 21,0);\n" "border-radius: 8;"
        )
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6.addWidget(self.frame_4, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_6.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_6.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_2.setStyleSheet(
            "background-color: rgb(20,20, 20);\n" "border-radius: 8;"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ConditionName = QtWidgets.QLineEdit(self.frame_2)
        self.ConditionName.setMinimumSize(QtCore.QSize(310, 26))
        self.ConditionName.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(0, 0, 0);"
        )
        self.ConditionName.setObjectName("ConditionName")
        self.gridLayout_3.addWidget(self.ConditionName, 0, 4, 1, 1)
        self.UniteToolButton = QtWidgets.QPushButton(self.frame_2)
        self.UniteToolButton.setObjectName("UniteToolButton")
        self.gridLayout_3.addWidget(self.UniteToolButton, 0, 9, 1, 1)
        self.OpenFolderButton = QtWidgets.QPushButton(self.frame_2)
        self.OpenFolderButton.setObjectName("OpenFolderButton")
        self.gridLayout_3.addWidget(self.OpenFolderButton, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_3.addItem(spacerItem3, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet('font: 12pt "MS Shell Dlg 2";')
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        self.BrakeButton = QtWidgets.QPushButton(self.frame_2)
        self.BrakeButton.setObjectName("BrakeButton")
        self.gridLayout_3.addWidget(self.BrakeButton, 0, 8, 1, 1)
        self.SplitterButton = QtWidgets.QPushButton(self.frame_2)
        self.SplitterButton.setObjectName("SplitterButton")
        self.gridLayout_3.addWidget(self.SplitterButton, 0, 10, 1, 1)
        self.SeparateViewsButton = QtWidgets.QPushButton(self.frame_2)
        self.SeparateViewsButton.setObjectName("SeparateViewsButton")
        self.gridLayout_3.addWidget(self.SeparateViewsButton, 0, 11, 1, 1)
        self.ImportImagesButton = QtWidgets.QPushButton(self.frame_2)
        self.ImportImagesButton.setStyleSheet("")
        self.ImportImagesButton.setObjectName("ImportImagesButton")
        self.gridLayout_3.addWidget(self.ImportImagesButton, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 2)
        self.FrameImportButtons = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.FrameImportButtons.sizePolicy().hasHeightForWidth()
        )
        self.FrameImportButtons.setSizePolicy(sizePolicy)
        self.FrameImportButtons.setStyleSheet(
            'font: 20pt "MS Shell Dlg 2";\n' "border-radius: 8;"
        )
        self.FrameImportButtons.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FrameImportButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FrameImportButtons.setObjectName("FrameImportButtons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.FrameImportButtons)
        self.horizontalLayout.setContentsMargins(60, 12, 60, 17)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ImportButton = QtWidgets.QPushButton(self.FrameImportButtons)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImportButton.sizePolicy().hasHeightForWidth())
        self.ImportButton.setSizePolicy(sizePolicy)
        self.ImportButton.setMinimumSize(QtCore.QSize(0, 50))
        self.ImportButton.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ImportButton.setFont(font)
        self.ImportButton.setStyleSheet(
            "background-color: rgb(20,20, 20);\n" "border-radius: 8;"
        )
        self.ImportButton.setObjectName("ImportButton")
        self.horizontalLayout.addWidget(self.ImportButton)
        self.CancelButton = QtWidgets.QPushButton(self.FrameImportButtons)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CancelButton.sizePolicy().hasHeightForWidth())
        self.CancelButton.setSizePolicy(sizePolicy)
        self.CancelButton.setMinimumSize(QtCore.QSize(0, 50))
        self.CancelButton.setMaximumSize(QtCore.QSize(16777215, 71))
        self.CancelButton.setStyleSheet(
            "background-color: rgb(20,20, 20);\n" "border-radius: 8;"
        )
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        self.gridLayout_2.addWidget(self.FrameImportButtons, 7, 0, 1, 2)
        self.CombinedChannelsLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.CombinedChannelsLabel.sizePolicy().hasHeightForWidth()
        )
        self.CombinedChannelsLabel.setSizePolicy(sizePolicy)
        self.CombinedChannelsLabel.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.CombinedChannelsLabel.setFont(font)
        self.CombinedChannelsLabel.setStyleSheet(
            "background-color: rgb(20,20, 20);\n"
            "\n"
            "    border: 0px solid;\n"
            "    border-top-left-radius: 20;\n"
            "    border-top-right-radius: 20;\n"
            "    border-bottom-right-radius: 4px;\n"
            "    border-bottom-left-radius: 4px;"
        )
        self.CombinedChannelsLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.CombinedChannelsLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.CombinedChannelsLabel.setLineWidth(0)
        self.CombinedChannelsLabel.setMidLineWidth(0)
        self.CombinedChannelsLabel.setScaledContents(False)
        self.CombinedChannelsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CombinedChannelsLabel.setIndent(-2)
        self.CombinedChannelsLabel.setObjectName("CombinedChannelsLabel")
        self.gridLayout_2.addWidget(self.CombinedChannelsLabel, 2, 0, 1, 1)
        self.Channels = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Channels.setFont(font)
        self.Channels.setStyleSheet(
            "background-color: rgb(20,20, 20);\n"
            "\n"
            "    border: 0px solid;\n"
            "    border-top-left-radius: 20;\n"
            "    border-top-right-radius: 20;\n"
            "    border-bottom-right-radius: 4px;\n"
            "    border-bottom-left-radius: 4px;"
        )
        self.Channels.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Channels.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Channels.setLineWidth(0)
        self.Channels.setMidLineWidth(0)
        self.Channels.setScaledContents(False)
        self.Channels.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Channels.setIndent(-2)
        self.Channels.setObjectName("Channels")
        self.gridLayout_2.addWidget(self.Channels, 2, 1, 1, 1)
        self.IndividualChannelsLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.IndividualChannelsLabel.sizePolicy().hasHeightForWidth()
        )
        self.IndividualChannelsLabel.setSizePolicy(sizePolicy)
        self.IndividualChannelsLabel.setMinimumSize(QtCore.QSize(0, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.IndividualChannelsLabel.setFont(font)
        self.IndividualChannelsLabel.setStyleSheet(
            "background-color: rgb(20,20, 20);\n"
            "\n"
            "    border: 0px solid;\n"
            "    border-top-left-radius: 20;\n"
            "    border-top-right-radius: 20;\n"
            "    border-bottom-right-radius: 4px;\n"
            "    border-bottom-left-radius: 4px;"
        )
        self.IndividualChannelsLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.IndividualChannelsLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.IndividualChannelsLabel.setLineWidth(0)
        self.IndividualChannelsLabel.setMidLineWidth(0)
        self.IndividualChannelsLabel.setScaledContents(False)
        self.IndividualChannelsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.IndividualChannelsLabel.setIndent(-2)
        self.IndividualChannelsLabel.setObjectName("IndividualChannelsLabel")
        self.gridLayout_2.addWidget(self.IndividualChannelsLabel, 5, 0, 1, 2)
        self.scrollAreaSingleChannels = QtWidgets.QScrollArea(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.scrollAreaSingleChannels.sizePolicy().hasHeightForWidth()
        )
        self.scrollAreaSingleChannels.setSizePolicy(sizePolicy)
        self.scrollAreaSingleChannels.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaSingleChannels.setWidgetResizable(True)
        self.scrollAreaSingleChannels.setObjectName("scrollAreaSingleChannels")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1142, 207))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth()
        )
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_ScrollArea = QtWidgets.QGridLayout(
            self.scrollAreaWidgetContents
        )
        self.gridLayout_ScrollArea.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_ScrollArea.setSpacing(0)
        self.gridLayout_ScrollArea.setObjectName("gridLayout_ScrollArea")
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setStyleSheet(
            "background-color: rgb(220,220, 220);\n" "border-radius: 8;"
        )
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(200, 161))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet(
            "background-color: rgba(21, 21, 21,0);\n" "border-radius: 8;"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_4.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_4.addItem(spacerItem6, 1, 0, 1, 1)
        self.gridLayout_ScrollArea.addWidget(self.frame_5, 0, 0, 1, 1)
        self.scrollAreaSingleChannels.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollAreaSingleChannels, 6, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(
            20,
            6,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.UniteToolButton.setText(_translate("Dialog", "Unite Tool"))
        self.OpenFolderButton.setText(_translate("Dialog", "Open Folder"))
        self.label.setText(_translate("Dialog", "New Condition Name:   "))
        self.BrakeButton.setText(_translate("Dialog", "Brake"))
        self.SplitterButton.setText(_translate("Dialog", "Splitter"))
        self.SeparateViewsButton.setText(_translate("Dialog", "Separate Views"))
        self.ImportImagesButton.setText(_translate("Dialog", "Import Images"))
        self.ImportButton.setText(_translate("Dialog", "Import"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
        self.CombinedChannelsLabel.setText(_translate("Dialog", "Combined Channells"))
        self.Channels.setText(_translate("Dialog", "View"))
        self.IndividualChannelsLabel.setText(
            _translate("Dialog", "Individual Channells")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
