# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sofia\Documents\Python\Python Scripts\topfluov1\UiAssets\swarm_plot_settings_widget.ui'
#
# Created by: PyQt6 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Swarm_Ui_Form(object):
    def setupUi(self, swarm_plot_settings_widget_form):
        swarm_plot_settings_widget_form.setObjectName("swarm_plot_settings_widget_form")
        swarm_plot_settings_widget_form.resize(355, 153)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(swarm_plot_settings_widget_form)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pg_2_swarmplot_plot_settings_1 = QtWidgets.QFrame(
            swarm_plot_settings_widget_form
        )
        self.pg_2_swarmplot_plot_settings_1.setObjectName(
            "pg_2_swarmplot_plot_settings_1"
        )
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(
            self.pg_2_swarmplot_plot_settings_1
        )
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pg_2_swarmplot_settings_1_left = QtWidgets.QFrame(
            self.pg_2_swarmplot_plot_settings_1
        )
        self.pg_2_swarmplot_settings_1_left.setObjectName(
            "pg_2_swarmplot_settings_1_left"
        )
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pg_2_swarmplot_settings_1_left)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pg2_graph_swarmplot_pallete_style_frame = QtWidgets.QFrame(
            self.pg_2_swarmplot_settings_1_left
        )
        self.pg2_graph_swarmplot_pallete_style_frame.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.pg2_graph_swarmplot_pallete_style_frame.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.pg2_graph_swarmplot_pallete_style_frame.setObjectName(
            "pg2_graph_swarmplot_pallete_style_frame"
        )
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(
            self.pg2_graph_swarmplot_pallete_style_frame
        )
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pg2_graph_pallete_style_label_swarmplot = QtWidgets.QLabel(
            self.pg2_graph_swarmplot_pallete_style_frame
        )
        self.pg2_graph_pallete_style_label_swarmplot.setMinimumSize(QtCore.QSize(0, 0))
        self.pg2_graph_pallete_style_label_swarmplot.setMaximumSize(
            QtCore.QSize(16777215, 16777215)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pg2_graph_pallete_style_label_swarmplot.setFont(font)
        self.pg2_graph_pallete_style_label_swarmplot.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.pg2_graph_pallete_style_label_swarmplot.setObjectName(
            "pg2_graph_pallete_style_label_swarmplot"
        )
        self.horizontalLayout_11.addWidget(self.pg2_graph_pallete_style_label_swarmplot)
        self.pg_2_graph_swarmplot_pallete_style_combobox = QtWidgets.QComboBox(
            self.pg2_graph_swarmplot_pallete_style_frame
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setMinimumSize(
            QtCore.QSize(75, 0)
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setMaximumSize(
            QtCore.QSize(75, 16777215)
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setObjectName(
            "pg_2_graph_swarmplot_pallete_style_combobox"
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.pg_2_graph_swarmplot_pallete_style_combobox.addItem("")
        self.horizontalLayout_11.addWidget(
            self.pg_2_graph_swarmplot_pallete_style_combobox
        )
        self.verticalLayout.addWidget(self.pg2_graph_swarmplot_pallete_style_frame)
        self.pg_2_color_graph_frame_swarmplot_plot = QtWidgets.QFrame(
            self.pg_2_swarmplot_settings_1_left
        )
        self.pg_2_color_graph_frame_swarmplot_plot.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.pg_2_color_graph_frame_swarmplot_plot.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.pg_2_color_graph_frame_swarmplot_plot.setObjectName(
            "pg_2_color_graph_frame_swarmplot_plot"
        )
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
            self.pg_2_color_graph_frame_swarmplot_plot
        )
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pg2_graph_color_swarmplot_plot = QtWidgets.QLabel(
            self.pg_2_color_graph_frame_swarmplot_plot
        )
        self.pg2_graph_color_swarmplot_plot.setMinimumSize(QtCore.QSize(0, 20))
        self.pg2_graph_color_swarmplot_plot.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pg2_graph_color_swarmplot_plot.setFont(font)
        self.pg2_graph_color_swarmplot_plot.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignCenter
            | QtCore.Qt.AlignmentFlag.AlignTop
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.pg2_graph_color_swarmplot_plot.setObjectName(
            "pg2_graph_color_swarmplot_plot"
        )
        self.horizontalLayout_2.addWidget(self.pg2_graph_color_swarmplot_plot)
        self.pg_2_graph_colors_pallete_2_swarmplot_plot = QtWidgets.QPushButton(
            self.pg_2_color_graph_frame_swarmplot_plot
        )
        self.pg_2_graph_colors_pallete_2_swarmplot_plot.setMinimumSize(
            QtCore.QSize(60, 0)
        )
        self.pg_2_graph_colors_pallete_2_swarmplot_plot.setMaximumSize(
            QtCore.QSize(60, 16777215)
        )
        self.pg_2_graph_colors_pallete_2_swarmplot_plot.setObjectName(
            "pg_2_graph_colors_pallete_2_swarmplot_plot"
        )
        self.horizontalLayout_2.addWidget(
            self.pg_2_graph_colors_pallete_2_swarmplot_plot
        )
        self.verticalLayout.addWidget(self.pg_2_color_graph_frame_swarmplot_plot)
        self.pg_2_graph_border_color_frame_swarmplot_plot = QtWidgets.QFrame(
            self.pg_2_swarmplot_settings_1_left
        )
        self.pg_2_graph_border_color_frame_swarmplot_plot.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.pg_2_graph_border_color_frame_swarmplot_plot.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.pg_2_graph_border_color_frame_swarmplot_plot.setObjectName(
            "pg_2_graph_border_color_frame_swarmplot_plot"
        )
        self.horizontalLayout = QtWidgets.QHBoxLayout(
            self.pg_2_graph_border_color_frame_swarmplot_plot
        )
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pg2_graph_border_color_swarmplot_plot = QtWidgets.QLabel(
            self.pg_2_graph_border_color_frame_swarmplot_plot
        )
        self.pg2_graph_border_color_swarmplot_plot.setMinimumSize(QtCore.QSize(0, 20))
        self.pg2_graph_border_color_swarmplot_plot.setMaximumSize(
            QtCore.QSize(16777215, 10)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pg2_graph_border_color_swarmplot_plot.setFont(font)
        self.pg2_graph_border_color_swarmplot_plot.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignCenter
            | QtCore.Qt.AlignmentFlag.AlignTop
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.pg2_graph_border_color_swarmplot_plot.setObjectName(
            "pg2_graph_border_color_swarmplot_plot"
        )
        self.horizontalLayout.addWidget(self.pg2_graph_border_color_swarmplot_plot)
        self.pg_2_graph_colors_pallete_swarmplot_plot = QtWidgets.QPushButton(
            self.pg_2_graph_border_color_frame_swarmplot_plot
        )
        self.pg_2_graph_colors_pallete_swarmplot_plot.setMinimumSize(
            QtCore.QSize(60, 0)
        )
        self.pg_2_graph_colors_pallete_swarmplot_plot.setMaximumSize(
            QtCore.QSize(60, 16777215)
        )
        self.pg_2_graph_colors_pallete_swarmplot_plot.setObjectName(
            "pg_2_graph_colors_pallete_swarmplot_plot"
        )
        self.horizontalLayout.addWidget(self.pg_2_graph_colors_pallete_swarmplot_plot)
        self.verticalLayout.addWidget(self.pg_2_graph_border_color_frame_swarmplot_plot)
        self.pg2_graph_border_width_frame_swarmplot = QtWidgets.QFrame(
            self.pg_2_swarmplot_settings_1_left
        )
        self.pg2_graph_border_width_frame_swarmplot.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.pg2_graph_border_width_frame_swarmplot.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.pg2_graph_border_width_frame_swarmplot.setObjectName(
            "pg2_graph_border_width_frame_swarmplot"
        )
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(
            self.pg2_graph_border_width_frame_swarmplot
        )
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pg2_graph_border_width_label_swarmplot = QtWidgets.QLabel(
            self.pg2_graph_border_width_frame_swarmplot
        )
        self.pg2_graph_border_width_label_swarmplot.setMinimumSize(QtCore.QSize(0, 20))
        self.pg2_graph_border_width_label_swarmplot.setMaximumSize(
            QtCore.QSize(16777215, 10)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pg2_graph_border_width_label_swarmplot.setFont(font)
        self.pg2_graph_border_width_label_swarmplot.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignCenter
            | QtCore.Qt.AlignmentFlag.AlignTop
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.pg2_graph_border_width_label_swarmplot.setObjectName(
            "pg2_graph_border_width_label_swarmplot"
        )
        self.horizontalLayout_4.addWidget(self.pg2_graph_border_width_label_swarmplot)
        self.pg2_graph_border_width_spinBox_swarmplot = QtWidgets.QSpinBox(
            self.pg2_graph_border_width_frame_swarmplot
        )
        self.pg2_graph_border_width_spinBox_swarmplot.setMinimumSize(
            QtCore.QSize(65, 0)
        )
        self.pg2_graph_border_width_spinBox_swarmplot.setMaximumSize(
            QtCore.QSize(65, 16777215)
        )
        self.pg2_graph_border_width_spinBox_swarmplot.setMinimum(0)
        self.pg2_graph_border_width_spinBox_swarmplot.setMaximum(100)
        self.pg2_graph_border_width_spinBox_swarmplot.setProperty("value", 3)
        self.pg2_graph_border_width_spinBox_swarmplot.setObjectName(
            "pg2_graph_border_width_spinBox_swarmplot"
        )
        self.horizontalLayout_4.addWidget(self.pg2_graph_border_width_spinBox_swarmplot)
        self.verticalLayout.addWidget(self.pg2_graph_border_width_frame_swarmplot)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_7.addWidget(self.pg_2_swarmplot_settings_1_left)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pg_2_settings_1_right_swarmplot_plot = QtWidgets.QFrame(
            self.pg_2_swarmplot_plot_settings_1
        )
        self.pg_2_settings_1_right_swarmplot_plot.setObjectName(
            "pg_2_settings_1_right_swarmplot_plot"
        )
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.pg_2_settings_1_right_swarmplot_plot
        )
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pg2_graph_index_frame_swarmplot = QtWidgets.QFrame(
            self.pg_2_settings_1_right_swarmplot_plot
        )
        self.pg2_graph_index_frame_swarmplot.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.pg2_graph_index_frame_swarmplot.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.pg2_graph_index_frame_swarmplot.setObjectName(
            "pg2_graph_index_frame_swarmplot"
        )
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(
            self.pg2_graph_index_frame_swarmplot
        )
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pg2_graph_index_label_swarmplot = QtWidgets.QLabel(
            self.pg2_graph_index_frame_swarmplot
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pg2_graph_index_label_swarmplot.setFont(font)
        self.pg2_graph_index_label_swarmplot.setObjectName(
            "pg2_graph_index_label_swarmplot"
        )
        self.horizontalLayout_3.addWidget(self.pg2_graph_index_label_swarmplot)
        self.pg2_graph_index_combobox_swarmplot = QtWidgets.QComboBox(
            self.pg2_graph_index_frame_swarmplot
        )
        self.pg2_graph_index_combobox_swarmplot.setMinimumSize(QtCore.QSize(60, 0))
        self.pg2_graph_index_combobox_swarmplot.setMaximumSize(
            QtCore.QSize(60, 16777215)
        )
        self.pg2_graph_index_combobox_swarmplot.setObjectName(
            "pg2_graph_index_combobox_swarmplot"
        )
        self.pg2_graph_index_combobox_swarmplot.addItem("")
        self.horizontalLayout_3.addWidget(self.pg2_graph_index_combobox_swarmplot)
        self.verticalLayout_2.addWidget(self.pg2_graph_index_frame_swarmplot)
        self.pg2_graph_size_frame_swarmplot = QtWidgets.QFrame(
            self.pg_2_settings_1_right_swarmplot_plot
        )
        self.pg2_graph_size_frame_swarmplot.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.pg2_graph_size_frame_swarmplot.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.pg2_graph_size_frame_swarmplot.setObjectName(
            "pg2_graph_size_frame_swarmplot"
        )
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(
            self.pg2_graph_size_frame_swarmplot
        )
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pg2_graph_size_label_swarmplot = QtWidgets.QLabel(
            self.pg2_graph_size_frame_swarmplot
        )
        self.pg2_graph_size_label_swarmplot.setMinimumSize(QtCore.QSize(0, 20))
        self.pg2_graph_size_label_swarmplot.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pg2_graph_size_label_swarmplot.setFont(font)
        self.pg2_graph_size_label_swarmplot.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignCenter
            | QtCore.Qt.AlignmentFlag.AlignTop
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.pg2_graph_size_label_swarmplot.setObjectName(
            "pg2_graph_size_label_swarmplot"
        )
        self.horizontalLayout_6.addWidget(self.pg2_graph_size_label_swarmplot)
        self.pg2_graph_size_spinBox_swarmplot = QtWidgets.QSpinBox(
            self.pg2_graph_size_frame_swarmplot
        )
        self.pg2_graph_size_spinBox_swarmplot.setMinimumSize(QtCore.QSize(65, 0))
        self.pg2_graph_size_spinBox_swarmplot.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pg2_graph_size_spinBox_swarmplot.setMinimum(0)
        self.pg2_graph_size_spinBox_swarmplot.setMaximum(100)
        self.pg2_graph_size_spinBox_swarmplot.setProperty("value", 20)
        self.pg2_graph_size_spinBox_swarmplot.setObjectName(
            "pg2_graph_size_spinBox_swarmplot"
        )
        self.horizontalLayout_6.addWidget(self.pg2_graph_size_spinBox_swarmplot)
        self.verticalLayout_2.addWidget(self.pg2_graph_size_frame_swarmplot)
        self.pg2_graph_orientaitno_frame_swarmplot = QtWidgets.QFrame(
            self.pg_2_settings_1_right_swarmplot_plot
        )
        self.pg2_graph_orientaitno_frame_swarmplot.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.pg2_graph_orientaitno_frame_swarmplot.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.pg2_graph_orientaitno_frame_swarmplot.setObjectName(
            "pg2_graph_orientaitno_frame_swarmplot"
        )
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(
            self.pg2_graph_orientaitno_frame_swarmplot
        )
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pg2_graph_orientation_label_swarmplot = QtWidgets.QLabel(
            self.pg2_graph_orientaitno_frame_swarmplot
        )
        self.pg2_graph_orientation_label_swarmplot.setMinimumSize(QtCore.QSize(0, 20))
        self.pg2_graph_orientation_label_swarmplot.setMaximumSize(
            QtCore.QSize(16777215, 10)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pg2_graph_orientation_label_swarmplot.setFont(font)
        self.pg2_graph_orientation_label_swarmplot.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignCenter
            | QtCore.Qt.AlignmentFlag.AlignTop
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.pg2_graph_orientation_label_swarmplot.setObjectName(
            "pg2_graph_orientation_label_swarmplot"
        )
        self.horizontalLayout_9.addWidget(self.pg2_graph_orientation_label_swarmplot)
        self.pg2_graph_orientaitno_combobox_swarmplot = QtWidgets.QComboBox(
            self.pg2_graph_orientaitno_frame_swarmplot
        )
        self.pg2_graph_orientaitno_combobox_swarmplot.setMinimumSize(
            QtCore.QSize(80, 0)
        )
        self.pg2_graph_orientaitno_combobox_swarmplot.setMaximumSize(
            QtCore.QSize(80, 16777215)
        )
        self.pg2_graph_orientaitno_combobox_swarmplot.setObjectName(
            "pg2_graph_orientaitno_combobox_swarmplot"
        )
        self.pg2_graph_orientaitno_combobox_swarmplot.addItem("")
        self.pg2_graph_orientaitno_combobox_swarmplot.addItem("")
        self.horizontalLayout_9.addWidget(self.pg2_graph_orientaitno_combobox_swarmplot)
        self.verticalLayout_2.addWidget(self.pg2_graph_orientaitno_frame_swarmplot)
        self.pg_2_custom_color_graph_frame_swarmplot = QtWidgets.QFrame(
            self.pg_2_settings_1_right_swarmplot_plot
        )
        self.pg_2_custom_color_graph_frame_swarmplot.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel
        )
        self.pg_2_custom_color_graph_frame_swarmplot.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised
        )
        self.pg_2_custom_color_graph_frame_swarmplot.setObjectName(
            "pg_2_custom_color_graph_frame_swarmplot"
        )
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(
            self.pg_2_custom_color_graph_frame_swarmplot
        )
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pg2_graph_color_swarmplot = QtWidgets.QLabel(
            self.pg_2_custom_color_graph_frame_swarmplot
        )
        self.pg2_graph_color_swarmplot.setMinimumSize(QtCore.QSize(0, 20))
        self.pg2_graph_color_swarmplot.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pg2_graph_color_swarmplot.setFont(font)
        self.pg2_graph_color_swarmplot.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignCenter
            | QtCore.Qt.AlignmentFlag.AlignTop
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.pg2_graph_color_swarmplot.setObjectName("pg2_graph_color_swarmplot")
        self.horizontalLayout_10.addWidget(self.pg2_graph_color_swarmplot)
        self.pg_2_graph_colors_pallete_swarmplot = QtWidgets.QPushButton(
            self.pg_2_custom_color_graph_frame_swarmplot
        )
        self.pg_2_graph_colors_pallete_swarmplot.setMinimumSize(QtCore.QSize(60, 0))
        self.pg_2_graph_colors_pallete_swarmplot.setMaximumSize(
            QtCore.QSize(60, 16777215)
        )
        self.pg_2_graph_colors_pallete_swarmplot.setObjectName(
            "pg_2_graph_colors_pallete_swarmplot"
        )
        self.horizontalLayout_10.addWidget(self.pg_2_graph_colors_pallete_swarmplot)
        self.verticalLayout_2.addWidget(self.pg_2_custom_color_graph_frame_swarmplot)
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_7.addWidget(self.pg_2_settings_1_right_swarmplot_plot)
        self.horizontalLayout_8.addWidget(self.pg_2_swarmplot_plot_settings_1)

        self.retranslateUi(swarm_plot_settings_widget_form)
        QtCore.QMetaObject.connectSlotsByName(swarm_plot_settings_widget_form)

    def retranslateUi(self, swarm_plot_settings_widget_form):
        _translate = QtCore.QCoreApplication.translate
        swarm_plot_settings_widget_form.setWindowTitle(
            _translate("swarm_plot_settings_widget_form", "Form")
        )
        self.pg2_graph_pallete_style_label_swarmplot.setText(
            _translate("swarm_plot_settings_widget_form", "Palette")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setCurrentText(
            _translate("swarm_plot_settings_widget_form", "Custom")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            0, _translate("swarm_plot_settings_widget_form", "Custom")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            1, _translate("swarm_plot_settings_widget_form", "deep")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            2, _translate("swarm_plot_settings_widget_form", "muted")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            3, _translate("swarm_plot_settings_widget_form", "bright")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            4, _translate("swarm_plot_settings_widget_form", "dark")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            5, _translate("swarm_plot_settings_widget_form", "colorblind")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            6, _translate("swarm_plot_settings_widget_form", "Paired")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            7, _translate("swarm_plot_settings_widget_form", "BuGn")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            8, _translate("swarm_plot_settings_widget_form", "GnBu")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            9, _translate("swarm_plot_settings_widget_form", "OrRd")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            10, _translate("swarm_plot_settings_widget_form", "PuBu")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            11, _translate("swarm_plot_settings_widget_form", "YlGn")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            12, _translate("swarm_plot_settings_widget_form", "YlGnBu")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            13, _translate("swarm_plot_settings_widget_form", "YlOrBr")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            14, _translate("swarm_plot_settings_widget_form", "YlOrRd")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            15, _translate("swarm_plot_settings_widget_form", "BrBG")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            16, _translate("swarm_plot_settings_widget_form", "PiYG")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            17, _translate("swarm_plot_settings_widget_form", "PRGn")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            18, _translate("swarm_plot_settings_widget_form", "PuOr")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            19, _translate("swarm_plot_settings_widget_form", "RdBu")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            20, _translate("swarm_plot_settings_widget_form", "RdGy")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            21, _translate("swarm_plot_settings_widget_form", "RdYlBu")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            22, _translate("swarm_plot_settings_widget_form", "RdYlGn")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            23, _translate("swarm_plot_settings_widget_form", "Spectral")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            24, _translate("swarm_plot_settings_widget_form", "Blues_d")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            25, _translate("swarm_plot_settings_widget_form", "coolwarm")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            26, _translate("swarm_plot_settings_widget_form", "pastel")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            27, _translate("swarm_plot_settings_widget_form", "husl")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            28, _translate("swarm_plot_settings_widget_form", "Set1")
        )
        self.pg_2_graph_swarmplot_pallete_style_combobox.setItemText(
            29, _translate("swarm_plot_settings_widget_form", "Set3")
        )
        self.pg2_graph_color_swarmplot_plot.setText(
            _translate("swarm_plot_settings_widget_form", "Color")
        )
        self.pg_2_graph_colors_pallete_2_swarmplot_plot.setText(
            _translate("swarm_plot_settings_widget_form", "Pallet")
        )
        self.pg2_graph_border_color_swarmplot_plot.setText(
            _translate("swarm_plot_settings_widget_form", "Border Color")
        )
        self.pg_2_graph_colors_pallete_swarmplot_plot.setText(
            _translate("swarm_plot_settings_widget_form", "Pallet")
        )
        self.pg2_graph_border_width_label_swarmplot.setText(
            _translate("swarm_plot_settings_widget_form", "Border width")
        )
        self.pg2_graph_index_label_swarmplot.setText(
            _translate("swarm_plot_settings_widget_form", "Index")
        )
        self.pg2_graph_index_combobox_swarmplot.setItemText(
            0, _translate("swarm_plot_settings_widget_form", "All")
        )
        self.pg2_graph_size_label_swarmplot.setText(
            _translate("swarm_plot_settings_widget_form", "Size")
        )
        self.pg2_graph_orientation_label_swarmplot.setText(
            _translate("swarm_plot_settings_widget_form", "Orientation")
        )
        self.pg2_graph_orientaitno_combobox_swarmplot.setItemText(
            0, _translate("swarm_plot_settings_widget_form", "Vertical")
        )
        self.pg2_graph_orientaitno_combobox_swarmplot.setItemText(
            1, _translate("swarm_plot_settings_widget_form", "Horizontal")
        )
        self.pg2_graph_color_swarmplot.setText(
            _translate("swarm_plot_settings_widget_form", "Color")
        )
        self.pg_2_graph_colors_pallete_swarmplot.setText(
            _translate("swarm_plot_settings_widget_form", "Pallet")
        )


if __name__ == "__main__":
    import sys

    # app = QtWidgets.QApplication(sys.argv)
    # swarm_plot_settings_widget_form = QtWidgets.QWidget()
    # ui = Ui_swarm_plot_settings_widget_form()
    # ui.setupUi(swarm_plot_settings_widget_form)
    # swarm_plot_settings_widget_form.show()
    # sys.exit(app.exec())
