# ../celer_sight_ai/UiAssets/OrganismSelectrionDiaolog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogMainSelection(object):
    def setupUi(self, DialogMainSelection):
        DialogMainSelection.setObjectName("DialogMainSelection")
        DialogMainSelection.resize(1191, 691)
        DialogMainSelection.setStyleSheet("background-color: rgba(255,255,255,255)")
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogMainSelection)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainframe = QtWidgets.QFrame(parent=DialogMainSelection)
        self.mainframe.setMinimumSize(QtCore.QSize(0, 100))
        self.mainframe.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.mainframe.setStyleSheet("background-color:rgb(250,250,250);")
        self.mainframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainframe.setObjectName("mainframe")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mainframe)
        self.gridLayout_3.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint
        )
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.mainframe)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1187, 687))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.mainframe, 0, 0, 1, 1)

        self.retranslateUi(DialogMainSelection)
        QtCore.QMetaObject.connectSlotsByName(DialogMainSelection)

    def retranslateUi(self, DialogMainSelection):
        _translate = QtCore.QCoreApplication.translate
        DialogMainSelection.setWindowTitle(_translate("DialogMainSelection", "Dialog"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DialogMainSelection = QtWidgets.QDialog()
    ui = Ui_DialogMainSelection()
    ui.setupUi(DialogMainSelection)
    DialogMainSelection.show()
    sys.exit(app.exec())
