# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\manos\Documents\topfluov3\UiAssets\AnalysisDialogUI.ui'
#
# Created by: PyQt6 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(398, 877)
        Dialog.setStyleSheet(
            "        QToolTip  \n"
            "         {  \n"
            "              border: 1px solid black;  \n"
            "              background-color: #ffa02f;  \n"
            "              padding: 1px;  \n"
            "              border-radius: 3px;  \n"
            "              opacity: 100;  \n"
            "         }  \n"
            "           \n"
            "         QWidget  \n"
            "         {  \n"
            "             color: #b1b1b1;  \n"
            "             background-color: #323232;  \n"
            "         }  \n"
            "           \n"
            "         QWidget:item:hover  \n"
            "         {  \n"
            "             background-color:QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "             color: #000000;  \n"
            "            border-radius:8px\n"
            "         }  \n"
            "           \n"
            "         QWidget:item:selected  \n"
            "         {  \n"
            "             background-color: rgb(168, 168, 168);\n"
            "            border-radius:8px\n"
            "\n"
            "         }  \n"
            "           \n"
            "\n"
            "        QMenuBar\n"
            "        {\n"
            "        background-color: rgb(255, 0, 0);  \n"
            "\n"
            "        }\n"
            "         QMenuBar::item  \n"
            "         {  \n"
            "             background: transparent;  \n"
            "\n"
            "         }  \n"
            "           \n"
            "         QMenuBar::item:selected  \n"
            "         {  \n"
            "             background: transparent;  \n"
            "             border: 1px solid #ffaa00;  \n"
            "         }  \n"
            "           \n"
            "         QMenuBar::item:pressed  \n"
            "         {  \n"
            "             background: #444;  \n"
            "             border: 1px solid #000;  \n"
            "             background-color: QLinearGradient(  \n"
            "                 x1:0, y1:0,  \n"
            "                 x2:0, y2:1,  \n"
            "                 stop:1 #212121,  \n"
            "                 stop:0.4 #343434/*,  \n"
            "                 stop:0.2 #343434,  \n"
            "                 stop:0.1 #ffaa00*/  \n"
            "             );  \n"
            "             margin-bottom:-1px;  \n"
            "             padding-bottom:1px;  \n"
            "         }  \n"
            "           \n"
            "         QMenu  \n"
            "         {  \n"
            "             border: 1px solid #000;  \n"
            "            background-color: rgb(170, 0, 0);\n"
            "         }  \n"
            "           \n"
            "         QMenu::item  \n"
            "         {  \n"
            "             padding: 2px 20px 2px 20px;  \n"
            "         }  \n"
            "           \n"
            "         QMenu::item:selected  \n"
            "         {  \n"
            "             color: #000000;  \n"
            "         }  \n"
            "           \n"
            "         QWidget:disabled  \n"
            "         {  \n"
            "             color: #404040;  \n"
            "             background-color: #323232;  \n"
            "         }  \n"
            "           \n"
            "         QAbstractItemView  \n"
            "         {  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);  \n"
            "         }  \n"
            "           \n"
            "         QWidget:focus  \n"
            "         {  \n"
            "             /*border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/  \n"
            "         }  \n"
            "           \n"
            "         QLineEdit  \n"
            "         {  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);  \n"
            "             padding: 1px;  \n"
            "             border-style: solid;  \n"
            "             border: 1px solid #1e1e1e;  \n"
            "             border-radius: 5;  \n"
            "         }  \n"
            "           \n"
            "         QPushButton  \n"
            "         {  \n"
            "             color: #b1b1b1;  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);  \n"
            "             border-width: 0px;  \n"
            "             border-color: #1e1e1e;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 6;  \n"
            "             padding: 3px;  \n"
            "             font-size: 12px;  \n"
            "             padding-left: 5px;  \n"
            "             padding-right: 5px;  \n"
            "         }  \n"
            "           \n"
            "         QPushButton:pressed  \n"
            "         {  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);  \n"
            "         }  \n"
            "           \n"
            "         QComboBox  \n"
            "         {  \n"
            "             selection-background-color: #ffaa00;  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);  \n"
            "             border-style: solid;  \n"
            "             border: 0px solid #1e1e1e;  \n"
            "             border-radius: 5;  \n"
            "         }  \n"
            "           \n"
            "         QComboBox:hover,QPushButton:hover  \n"
            "         {  \n"
            "             border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "         }  \n"
            "           \n"
            "           \n"
            "         QComboBox:on  \n"
            "         {  \n"
            "             padding-top: 3px;  \n"
            "             padding-left: 4px;  \n"
            "             background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);  \n"
            "             selection-background-color: #ffaa00;\n"
            "         }  \n"
            "           \n"
            "         QComboBox QAbstractItemView  \n"
            "         {  \n"
            "             border: 2px solid darkgray;  \n"
            "             selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "         }  \n"
            "           \n"
            "         QComboBox::drop-down  \n"
            "         {  \n"
            "              subcontrol-origin: padding;  \n"
            "              subcontrol-position: top right;  \n"
            "              width: 15px;  \n"
            "           \n"
            "              border-left-width: 0px;  \n"
            "              border-left-color: darkgray;  \n"
            "              border-left-style: solid; /* just a single line */  \n"
            "              border-top-right-radius: 3px; /* same radius as the QComboBox */  \n"
            "              border-bottom-right-radius: 3px;  \n"
            "          }  \n"
            "           \n"
            "         QComboBox::down-arrow  \n"
            "         {  \n"
            "              image: url(:/down_arrow.png);  \n"
            "         }  \n"
            "           \n"
            "         QGroupBox:focus  \n"
            "         {  \n"
            "         border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "         }  \n"
            "           \n"
            "         QTextEdit:focus  \n"
            "         {  \n"
            "             border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar:horizontal {  \n"
            "              border: 1px solid #222222;  \n"
            "              background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);  \n"
            "              height: 7px;  \n"
            "              margin: 0px 16px 0 16px;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::handle:horizontal  \n"
            "         {  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);  \n"
            "               min-height: 20px;  \n"
            "               border-radius: 2px;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::add-line:horizontal {  \n"
            "               border: 1px solid #1b1b19;  \n"
            "               border-radius: 2px;  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "               width: 14px;  \n"
            "               subcontrol-position: right;  \n"
            "               subcontrol-origin: margin;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::sub-line:horizontal {  \n"
            "               border: 1px solid #1b1b19;  \n"
            "               border-radius: 2px;  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "               width: 14px;  \n"
            "              subcontrol-position: left;  \n"
            "              subcontrol-origin: margin;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal  \n"
            "         {  \n"
            "               border: 1px solid black;  \n"
            "               width: 1px;  \n"
            "               height: 1px;  \n"
            "               background: white;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal  \n"
            "         {  \n"
            "               background: none;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar:vertical  \n"
            "         {  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);  \n"
            "               width: 7px;  \n"
            "               margin: 16px 0 16px 0;  \n"
            "               border: 1px solid #222222;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::handle:vertical  \n"
            "         {  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);  \n"
            "               min-height: 20px;  \n"
            "               border-radius: 2px;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::add-line:vertical  \n"
            "         {  \n"
            "               border: 1px solid #1b1b19;  \n"
            "               border-radius: 2px;  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);  \n"
            "               height: 14px;  \n"
            "               subcontrol-position: bottom;  \n"
            "               subcontrol-origin: margin;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::sub-line:vertical  \n"
            "         {  \n"
            "               border: 1px solid #1b1b19;  \n"
            "               border-radius: 2px;  \n"
            "               background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);  \n"
            "               height: 14px;  \n"
            "               subcontrol-position: top;  \n"
            "               subcontrol-origin: margin;  \n"
            "         }  \n"
            "           \n"
            "         QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical  \n"
            "         {  \n"
            "               border: 1px solid black;  \n"
            "               width: 1px;  \n"
            "               height: 1px;  \n"
            "               background: white;  \n"
            "         }  \n"
            "           \n"
            "           \n"
            "         QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical  \n"
            "         {  \n"
            "               background: none;  \n"
            "         }  \n"
            "           \n"
            "         QTextEdit  \n"
            "         {  \n"
            "             background-color: #242424;  \n"
            "         }  \n"
            "           \n"
            "         QPlainTextEdit  \n"
            "         {  \n"
            "             background-color: #242424;  \n"
            "         }  \n"
            "           \n"
            "         QHeaderView::section  \n"
            "         {  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);  \n"
            "             color: white;  \n"
            "             padding-left: 4px;  \n"
            "             border: 1px solid #6c6c6c;  \n"
            "         }  \n"
            "           \n"
            "         QCheckBox:disabled  \n"
            "         {  \n"
            "         color: #414141;  \n"
            "         }  \n"
            "           \n"
            "         QDockWidget::title  \n"
            "         {  \n"
            "             text-align: center;  \n"
            "             spacing: 3px; /* spacing between items in the tool bar */  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);  \n"
            "         }  \n"
            "           \n"
            "         QDockWidget::close-button, QDockWidget::float-button  \n"
            "         {  \n"
            "             text-align: center;  \n"
            "             spacing: 1px; /* spacing between items in the tool bar */  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);  \n"
            "         }  \n"
            "           \n"
            "         QDockWidget::close-button:hover, QDockWidget::float-button:hover  \n"
            "         {  \n"
            "             background: #242424;  \n"
            "         }  \n"
            "           \n"
            "         QDockWidget::close-button:pressed, QDockWidget::float-button:pressed  \n"
            "         {  \n"
            "             padding: 1px -1px -1px 1px;  \n"
            "         }  \n"
            "           \n"
            "         QMainWindow::separator  \n"
            "         {  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);  \n"
            "             color: white;  \n"
            "             padding-left: 4px;  \n"
            "             border: 1px solid #4c4c4c;  \n"
            "             spacing: 3px; /* spacing between items in the tool bar */  \n"
            "         }  \n"
            "           \n"
            "         QMainWindow::separator:hover  \n"
            "         {  \n"
            "           \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);  \n"
            "             color: white;  \n"
            "             padding-left: 4px;  \n"
            "             border: 1px solid #6c6c6c;  \n"
            "             spacing: 3px; /* spacing between items in the tool bar */  \n"
            "         }  \n"
            "           \n"
            "\n"
            "         QToolBar\n"
            "         {  \n"
            "              \n"
            "            background-color: rgba(255,255, 255,50);\n"
            "         }  \n"
            "           \n"
            "         QToolBar::handle  \n"
            "         {  \n"
            "        background-color: rgb(154, 154, 154);\n"
            "        color: rgb(255, 255, 255);\n"
            "         }  \n"
            "        QToolButton\n"
            "        {\n"
            "        margin: 0px 2px;\n"
            "        background-color: rgba(0, 0, 0,10);\n"
            "        border-radius: 5px;\n"
            "        border: 1px solid rgba(255, 255, 255,0);\n"
            "\n"
            "        }\n"
            "        QToolButton::checked\n"
            "        {\n"
            "        margin: 0px 2px;\n"
            "        background-color: rgba(0, 0, 0,150);\n"
            "        border-radius: 5px;\n"
            "        border: 1px solid rgba(255, 255, 255,190);\n"
            "        \n"
            "        }\n"
            "        QToolButton:!selected:hover\n"
            "        {\n"
            "        margin: 0px 2px;\n"
            "        background-color: rgba(0, 0, 0,100);\n"
            "        border-radius: 5px;\n"
            "        border: 1px solid rgba(255, 255, 255,40);\n"
            "        }\n"
            "\n"
            "        QToolButton:selected:hover\n"
            "        {\n"
            "        margin: 0px 2px;\n"
            "        background-color: rgba(0, 0, 0,150);\n"
            "        border-radius: 5px;\n"
            "        border: 1px solid rgba(255, 255, 255,190);\n"
            "        \n"
            "        }\n"
            "\n"
            "         QMenu::separator  \n"
            "         {  \n"
            "             height: 2px;  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);  \n"
            "             color: white;  \n"
            "             padding-left: 4px;  \n"
            "             margin-left: 10px;  \n"
            "             margin-right: 5px;  \n"
            "         }  \n"
            "           \n"
            "         QProgressBar  \n"
            "         {  \n"
            "             border: 2px solid grey;  \n"
            "             border-radius: 5px;  \n"
            "             text-align: center;  \n"
            "         }  \n"
            "           \n"
            "         QProgressBar::chunk  \n"
            "         {  \n"
            "             background-color: #d7801a;  \n"
            "             width: 2.15px;  \n"
            "             margin: 0.5px;  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab {  \n"
            "             color: #b1b1b1;  \n"
            "             border: 0px solid #444;  \n"
            "             border-bottom-style: none;  \n"
            "             background-color: #323232;  \n"
            "             padding-left: 10px;  \n"
            "             padding-right: 10px;  \n"
            "             padding-top: 3px;  \n"
            "             padding-bottom: 2px;  \n"
            "             margin-right: -1px;  \n"
            "         }  \n"
            "           \n"
            "         QTabWidget::pane {  \n"
            "             border: 0px solid #444;  \n"
            "             top: 1px; \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:last  \n"
            "         {  \n"
            "             margin-right: 0; /* the last selected tab has nothing to overlap with on the right */  \n"
            "             border-top-right-radius: 3px;  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:first:!selected  \n"
            "         {  \n"
            "          margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */  \n"
            "           \n"
            "           \n"
            "             border-top-left-radius: 3px;  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:!selected  \n"
            "         {  \n"
            "             color: #b1b1b1;  \n"
            "             border-bottom-style: solid;  \n"
            "             margin-top: 3px;  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #1c0009);  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:selected  \n"
            "         {  \n"
            "             border-top-left-radius: 3px;  \n"
            "             border-top-right-radius: 3px;  \n"
            "             margin-bottom: 0px;  \n"
            "         }  \n"
            "           \n"
            "         QTabBar::tab:!selected:hover  \n"
            "         {  \n"
            "             /*border-top: 2px solid #ffaa00;  \n"
            "             padding-bottom: 3px;*/  \n"
            "             border-top-left-radius: 3px;  \n"
            "             border-top-right-radius: 3px;  \n"
            "             background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #350012, stop:0.2 #4e001a, stop:0.1 #4e001a);  \n"
            "         }  \n"
            "           \n"
            "\n"
            "         QTableWidget::item {  \n"
            "              background-color: #FFFFFF  \n"
            "          }  \n"
            "\n"
            "         QTabBar::tab { height: 30px; width: 200px; }  \n"
            "          \n"
            "         QScrollBar { \n"
            "             border: rgba(255, 255, 255,0); \n"
            "         } \n"
            "\n"
            "         QGroupBox {  \n"
            "             border: rgba(255, 255, 255,0); \n"
            "         }  \n"
            "\n"
            "\n"
            "\n"
            "\n"
            "        QSlider::groove{\n"
            "        background-color: white;\n"
            "        border: 0px solid black;\n"
            "        height: 5px;\n"
            "        border-radius: 1px;\n"
            "        }\n"
            "\n"
            "        QSlider::handle{\n"
            "        background-color: black;\n"
            "        border: 2px solid black; \n"
            "        width: 16px; \n"
            "        height: 20px; \n"
            "        line-height: 20px; \n"
            "        margin-top: -10px; \n"
            "        margin-bottom: -10px; \n"
            "        border-radius: 10px;\n"
            "\n"
            "\n"
            "\n"
            "        \n"
            "        }\n"
            "        QGroupBox {\n"
            "            border: 1px solid;\n"
            "            border-color: rgb(20, 20, 20);\n"
            "            margin-top: 20px;\n"
            "            border-top-left-radius: 15px;\n"
            "            border-top-right-radius:15px;\n"
            "            border-bottom-left-radius: 15px;\n"
            "            border-bottom-right-radius: 15px;\n"
            "            background-color: rgb(90, 90, 90);\n"
            "        }\n"
            "        QGroupBox::title {\n"
            "            font-size: 12px;\n"
            "            border-top-color: rgb(255, 255, 255);\n"
            "            subcontrol-origin: margin;\n"
            "            subcontrol-position: top left;\n"
            "            border-top-left-radius: 15px;\n"
            "            border-top-right-radius:15px;\n"
            "            padding: 2px 10px;\n"
            "            background-color: rgba(255, 255, 255,0);\n"
            "            color:rgba(255, 255, 255,220);\n"
            "        }\n"
            "\n"
            "\n"
            "        QGroupBox::indicator{\n"
            "        background-color: rgba(0, 170, 127,0);\n"
            "        color: rgba(85, 255, 0,0);\n"
            "        }\n"
            "\n"
            "\n"
            "    QWidget::item{\n"
            "            color: rgb(255,0,0);\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "        \n"
            "\n"
            "        QGroupBox {\n"
            "            border: 1px solid;\n"
            "            border-color: rgb(20, 20, 20);\n"
            "            margin-top: 20px;\n"
            "            border-top-left-radius: 15px;\n"
            "            border-top-right-radius:15px;\n"
            "            border-bottom-left-radius: 15px;\n"
            "            border-bottom-right-radius: 15px;\n"
            "            background-color: rgb(90, 90, 90);\n"
            "        }\n"
            "        QGroupBox::title {\n"
            "            font-size: 12px;\n"
            "            border-top-color: rgb(255, 255, 255);\n"
            "            subcontrol-origin: margin;\n"
            "            subcontrol-position: top left;\n"
            "            border-top-left-radius: 15px;\n"
            "            border-top-right-radius:15px;\n"
            "            padding: 2px 10px;\n"
            "            background-color: rgba(255, 255, 255,0);\n"
            "            color:rgba(255, 255, 255,220);\n"
            "        }\n"
            "\n"
            "\n"
            "        QGroupBox::indicator{\n"
            "        background-color: rgba(0, 170, 127,0);\n"
            "        color: rgba(85, 255, 0,0);\n"
            "        }\n"
            "\n"
            "\n"
            "    QWidget::item{\n"
            "            color: rgb(255,0,0);\n"
            "}\n"
            "\n"
            "\n"
            "QCheckBox{\n"
            "background-color:rgba(0,0,0,0);\n"
            "}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "QLabel{\n"
            "background-color:rgba(0,0,0,0);\n"
            "color:rgb(220,220,220);\n"
            "}\n"
            "        \n"
            "    QSlider{\n"
            "background-color:rgba(0,0,0,0);\n"
            "}\n"
            "        QSlider::sub-page{\n"
            "         background-color:rgb(210, 210, 210);\n"
            "margin-left:4px;\n"
            "\n"
            "        }\n"
            "        QSlider::groove{\n"
            "        background-color:rgb(170, 170, 170);\n"
            "        border: 0px solid black;\n"
            "        height: 4px;\n"
            "        border-radius: 2px;\n"
            "margin-left:4px;\n"
            "\n"
            "        }\n"
            "\n"
            "        QSlider::handle{\n"
            "        background-color: white;\n"
            "        border: 0px solid black; \n"
            "        width: 17px; \n"
            "        height: 14px; \n"
            "        line-height: 6px; \n"
            "        margin-top: -6px; \n"
            "        margin-bottom: -6px; \n"
            "        border-radius:8px;\n"
            "        \n"
            "}"
        )
        self.gridLayout_6 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.contours_groupbox = QtWidgets.QGroupBox(Dialog)
        self.contours_groupbox.setMinimumSize(QtCore.QSize(0, 132))
        self.contours_groupbox.setObjectName("contours_groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.contours_groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetNoConstraint
        )
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.edge_count_box = QtWidgets.QCheckBox(self.contours_groupbox)
        self.edge_count_box.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.edge_count_box.setStyleSheet("")
        self.edge_count_box.setObjectName("edge_count_box")
        self.verticalLayout_6.addWidget(self.edge_count_box)
        self.strain_size_box = QtWidgets.QCheckBox(self.contours_groupbox)
        self.strain_size_box.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.strain_size_box.setChecked(False)
        self.strain_size_box.setObjectName("strain_size_box")
        self.verticalLayout_6.addWidget(self.strain_size_box)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 2)
        self.hightlight_manimum = QtWidgets.QPushButton(self.contours_groupbox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.hightlight_manimum.setFont(font)
        self.hightlight_manimum.setObjectName("hightlight_manimum")
        self.gridLayout.addWidget(self.hightlight_manimum, 0, 2, 1, 1)
        self.minimum_size_label = QtWidgets.QLabel(self.contours_groupbox)
        self.minimum_size_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minimum_size_label.setObjectName("minimum_size_label")
        self.gridLayout.addWidget(self.minimum_size_label, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.minimum_size_nmbr = QtWidgets.QSpinBox(self.contours_groupbox)
        self.minimum_size_nmbr.setMinimum(-50)
        self.minimum_size_nmbr.setMaximum(50)
        self.minimum_size_nmbr.setObjectName("minimum_size_nmbr")
        self.verticalLayout_5.addWidget(self.minimum_size_nmbr)
        self.maximum_size_nmbr = QtWidgets.QSpinBox(self.contours_groupbox)
        self.maximum_size_nmbr.setObjectName("maximum_size_nmbr")
        self.verticalLayout_5.addWidget(self.maximum_size_nmbr)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 2, 1)
        self.hightlight_maximum = QtWidgets.QPushButton(self.contours_groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hightlight_maximum.setFont(font)
        self.hightlight_maximum.setObjectName("hightlight_maximum")
        self.gridLayout.addWidget(self.hightlight_maximum, 1, 2, 2, 1)
        self.maximum_size_label = QtWidgets.QLabel(self.contours_groupbox)
        self.maximum_size_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maximum_size_label.setObjectName("maximum_size_label")
        self.gridLayout.addWidget(self.maximum_size_label, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.contours_groupbox, 15, 0, 1, 4)
        self.ColocalizationGroupBox = QtWidgets.QGroupBox(Dialog)
        self.ColocalizationGroupBox.setMinimumSize(QtCore.QSize(0, 175))
        self.ColocalizationGroupBox.setObjectName("ColocalizationGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ColocalizationGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MultipleColocMethodsLable = QtWidgets.QLabel(self.ColocalizationGroupBox)
        self.MultipleColocMethodsLable.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.MultipleColocMethodsLable.setObjectName("MultipleColocMethodsLable")
        self.gridLayout_3.addWidget(self.MultipleColocMethodsLable, 2, 0, 1, 1)
        self.MultipleColocMethodsListWIdget = QtWidgets.QListWidget(
            self.ColocalizationGroupBox
        )
        self.MultipleColocMethodsListWIdget.setObjectName(
            "MultipleColocMethodsListWIdget"
        )
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.MultipleColocMethodsListWIdget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.MultipleColocMethodsListWIdget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.MultipleColocMethodsListWIdget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.MultipleColocMethodsListWIdget.addItem(item)
        self.gridLayout_3.addWidget(self.MultipleColocMethodsListWIdget, 4, 0, 1, 2)
        self.ComboboxOneMethodColoc = QtWidgets.QComboBox(self.ColocalizationGroupBox)
        self.ComboboxOneMethodColoc.setObjectName("ComboboxOneMethodColoc")
        self.ComboboxOneMethodColoc.addItem("")
        self.ComboboxOneMethodColoc.addItem("")
        self.gridLayout_3.addWidget(self.ComboboxOneMethodColoc, 0, 1, 1, 1)
        self.ColocMultipleCheckbox = QtWidgets.QCheckBox(self.ColocalizationGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ColocMultipleCheckbox.sizePolicy().hasHeightForWidth()
        )
        self.ColocMultipleCheckbox.setSizePolicy(sizePolicy)
        self.ColocMultipleCheckbox.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ColocMultipleCheckbox.setText("")
        self.ColocMultipleCheckbox.setObjectName("ColocMultipleCheckbox")
        self.gridLayout_3.addWidget(self.ColocMultipleCheckbox, 2, 1, 1, 1)
        self.SingleColocMethodLabel = QtWidgets.QLabel(self.ColocalizationGroupBox)
        self.SingleColocMethodLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.SingleColocMethodLabel.setObjectName("SingleColocMethodLabel")
        self.gridLayout_3.addWidget(self.SingleColocMethodLabel, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.ColocalizationGroupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.ColocAutoThresholdCheckbox = QtWidgets.QCheckBox(
            self.ColocalizationGroupBox
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ColocAutoThresholdCheckbox.sizePolicy().hasHeightForWidth()
        )
        self.ColocAutoThresholdCheckbox.setSizePolicy(sizePolicy)
        self.ColocAutoThresholdCheckbox.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ColocAutoThresholdCheckbox.setText("")
        self.ColocAutoThresholdCheckbox.setObjectName("ColocAutoThresholdCheckbox")
        self.gridLayout_3.addWidget(self.ColocAutoThresholdCheckbox, 3, 1, 1, 1)
        self.gridLayout_6.addWidget(self.ColocalizationGroupBox, 14, 0, 1, 4)
        self.bg_thresh_groupbox_2 = QtWidgets.QGroupBox(Dialog)
        self.bg_thresh_groupbox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.bg_thresh_groupbox_2.setObjectName("bg_thresh_groupbox_2")
        self.gridLayout_subackground2 = QtWidgets.QGridLayout(self.bg_thresh_groupbox_2)
        self.gridLayout_subackground2.setObjectName("gridLayout_subackground2")
        self.substract_background_2 = QtWidgets.QLabel(self.bg_thresh_groupbox_2)
        self.substract_background_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.substract_background_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.substract_background_2.setObjectName("substract_background_2")
        self.gridLayout_subackground2.addWidget(self.substract_background_2, 4, 0, 1, 1)
        self.adjust_threshold_2 = QtWidgets.QLabel(self.bg_thresh_groupbox_2)
        self.adjust_threshold_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.adjust_threshold_2.setObjectName("adjust_threshold_2")
        self.gridLayout_subackground2.addWidget(self.adjust_threshold_2, 5, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.substract_background_nmbr_2 = QtWidgets.QSpinBox(self.bg_thresh_groupbox_2)
        self.substract_background_nmbr_2.setMaximum(70)
        self.substract_background_nmbr_2.setObjectName("substract_background_nmbr_2")
        self.verticalLayout_7.addWidget(self.substract_background_nmbr_2)
        self.adjust_threshold_nmbr_2 = QtWidgets.QSpinBox(self.bg_thresh_groupbox_2)
        self.adjust_threshold_nmbr_2.setMaximum(250)
        self.adjust_threshold_nmbr_2.setObjectName("adjust_threshold_nmbr_2")
        self.verticalLayout_7.addWidget(self.adjust_threshold_nmbr_2)
        self.gridLayout_subackground2.addLayout(self.verticalLayout_7, 4, 4, 2, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetNoConstraint
        )
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.substract_background_sldr_2 = QtWidgets.QSlider(self.bg_thresh_groupbox_2)
        self.substract_background_sldr_2.setMinimum(1)
        self.substract_background_sldr_2.setMaximum(70)
        self.substract_background_sldr_2.setPageStep(1)
        self.substract_background_sldr_2.setProperty("value", 6)
        self.substract_background_sldr_2.setOrientation(
            QtCore.Qt.Orientation.Horizontal
        )
        self.substract_background_sldr_2.setObjectName("substract_background_sldr_2")
        self.verticalLayout_8.addWidget(self.substract_background_sldr_2)
        self.adjust_threshold_sldr_2 = QtWidgets.QSlider(self.bg_thresh_groupbox_2)
        self.adjust_threshold_sldr_2.setMaximum(250)
        self.adjust_threshold_sldr_2.setProperty("value", 30)
        self.adjust_threshold_sldr_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.adjust_threshold_sldr_2.setObjectName("adjust_threshold_sldr_2")
        self.verticalLayout_8.addWidget(self.adjust_threshold_sldr_2)
        self.gridLayout_subackground2.addLayout(self.verticalLayout_8, 4, 1, 2, 2)
        self.gridLayout_6.addWidget(self.bg_thresh_groupbox_2, 12, 0, 1, 4)
        self.bg_thresh_groupbox = QtWidgets.QGroupBox(Dialog)
        self.bg_thresh_groupbox.setMinimumSize(QtCore.QSize(0, 100))
        self.bg_thresh_groupbox.setObjectName("bg_thresh_groupbox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.bg_thresh_groupbox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.substract_background = QtWidgets.QLabel(self.bg_thresh_groupbox)
        self.substract_background.setMaximumSize(QtCore.QSize(100, 16777215))
        self.substract_background.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.substract_background.setObjectName("substract_background")
        self.gridLayout_5.addWidget(self.substract_background, 4, 0, 1, 1)
        self.adjust_threshold = QtWidgets.QLabel(self.bg_thresh_groupbox)
        self.adjust_threshold.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.adjust_threshold.setObjectName("adjust_threshold")
        self.gridLayout_5.addWidget(self.adjust_threshold, 5, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.substract_background_nmbr = QtWidgets.QSpinBox(self.bg_thresh_groupbox)
        self.substract_background_nmbr.setMaximum(70)
        self.substract_background_nmbr.setObjectName("substract_background_nmbr")
        self.verticalLayout_2.addWidget(self.substract_background_nmbr)
        self.adjust_threshold_nmbr = QtWidgets.QSpinBox(self.bg_thresh_groupbox)
        self.adjust_threshold_nmbr.setMaximum(250)
        self.adjust_threshold_nmbr.setObjectName("adjust_threshold_nmbr")
        self.verticalLayout_2.addWidget(self.adjust_threshold_nmbr)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 4, 4, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetNoConstraint
        )
        self.verticalLayout.setObjectName("verticalLayout")
        self.substract_background_sldr = QtWidgets.QSlider(self.bg_thresh_groupbox)
        self.substract_background_sldr.setMinimum(1)
        self.substract_background_sldr.setMaximum(70)
        self.substract_background_sldr.setPageStep(1)
        self.substract_background_sldr.setProperty("value", 6)
        self.substract_background_sldr.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.substract_background_sldr.setObjectName("substract_background_sldr")
        self.verticalLayout.addWidget(self.substract_background_sldr)
        self.adjust_threshold_sldr = QtWidgets.QSlider(self.bg_thresh_groupbox)
        self.adjust_threshold_sldr.setMaximum(250)
        self.adjust_threshold_sldr.setProperty("value", 30)
        self.adjust_threshold_sldr.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.adjust_threshold_sldr.setObjectName("adjust_threshold_sldr")
        self.verticalLayout.addWidget(self.adjust_threshold_sldr)
        self.gridLayout_5.addLayout(self.verticalLayout, 4, 1, 2, 2)
        self.gridLayout_6.addWidget(self.bg_thresh_groupbox, 11, 0, 1, 4)
        self.previous_image = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.previous_image.setFont(font)
        self.previous_image.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.previous_image.setIconSize(QtCore.QSize(16, 17))
        self.previous_image.setObjectName("previous_image")
        self.gridLayout_6.addWidget(self.previous_image, 5, 0, 1, 1)
        self.gridLayoutChannelsToMeasure = QtWidgets.QGridLayout()
        self.gridLayoutChannelsToMeasure.setSpacing(0)
        self.gridLayoutChannelsToMeasure.setObjectName("gridLayoutChannelsToMeasure")
        self.parameters_label_channel_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.parameters_label_channel_2.setFont(font)
        self.parameters_label_channel_2.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.parameters_label_channel_2.setObjectName("parameters_label_channel_2")
        self.gridLayoutChannelsToMeasure.addWidget(
            self.parameters_label_channel_2, 4, 0, 1, 1
        )
        self.parameters_label_channel_1 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.parameters_label_channel_1.setFont(font)
        self.parameters_label_channel_1.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.parameters_label_channel_1.setObjectName("parameters_label_channel_1")
        self.gridLayoutChannelsToMeasure.addWidget(
            self.parameters_label_channel_1, 2, 0, 1, 1
        )
        self.LayoutContainerForColorButtonsAnalysis = QtWidgets.QGridLayout()
        self.LayoutContainerForColorButtonsAnalysis.setObjectName(
            "LayoutContainerForColorButtonsAnalysis"
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization = (
            QtWidgets.QPushButton(Dialog)
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AnalysisDialog__blue_channel_button_visual_colocalization.sizePolicy().hasHeightForWidth()
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setSizePolicy(
            sizePolicy
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setMinimumSize(
            QtCore.QSize(50, 20)
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setMaximumSize(
            QtCore.QSize(75, 16777215)
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setBaseSize(
            QtCore.QSize(0, 0)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setFont(font)
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setStyleSheet(
            "\n"
            "QPushButton{\n"
            "        color: rgb(255, 255, 255);\n"
            "\n"
            "             border-width: 2px;  \n"
            "            border-left-width: 0px;\n"
            "             border-style: solid;  \n"
            "             border-radius: 10;  \n"
            "             padding: 3px;  \n"
            "                border-top-left-radius: 0;\n"
            "                border-bottom-left-radius: 0;\n"
            "             padding-left: 5px;  \n"
            "             padding-right: 5px;  \n"
            "        background-color: rgb(5,5 , 255);\n"
            "        border-color: rgb(5, 5, 20);\n"
            "        font-size: 19px;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover{\n"
            "    border-width: 2px;  \n"
            "    border-color: rgb(0, 0, 200);\n"
            "    border-left-width: 0 px;\n"
            "    border-style: solid;  \n"
            "}\n"
            "\n"
            "QPushButton:checked{\n"
            "    border-width: 2px;  \n"
            "    background-color:rgb(40,40,80);\n"
            "    border-left-width: 0 px;\n"
            "    border-style: solid;  \n"
            "}\n"
            ""
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setCheckable(
            True
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setChecked(False)
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setAutoExclusive(
            False
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setObjectName(
            "AnalysisDialog__blue_channel_button_visual_colocalization"
        )
        self.LayoutContainerForColorButtonsAnalysis.addWidget(
            self.AnalysisDialog__blue_channel_button_visual_colocalization, 0, 2, 1, 1
        )
        self.AnalysisDialog_green_channel_button_visual = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AnalysisDialog_green_channel_button_visual.sizePolicy().hasHeightForWidth()
        )
        self.AnalysisDialog_green_channel_button_visual.setSizePolicy(sizePolicy)
        self.AnalysisDialog_green_channel_button_visual.setMinimumSize(
            QtCore.QSize(50, 24)
        )
        self.AnalysisDialog_green_channel_button_visual.setMaximumSize(
            QtCore.QSize(75, 16777215)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AnalysisDialog_green_channel_button_visual.setFont(font)
        self.AnalysisDialog_green_channel_button_visual.setStyleSheet(
            "\n"
            "QPushButton{\n"
            "            color: rgb(255, 255, 255);\n"
            "\n"
            "             border-width: 2px;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 0;  \n"
            "             padding: 3px;  \n"
            "\n"
            "             padding-left: 5px;  \n"
            "             padding-right: 5px;  \n"
            "            background-color: rgb(5, 255, 5);\n"
            "            border-color: rgb(0, 20, 0);\n"
            "            font-size: 19px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    border-width: 2px;  \n"
            "    border-color: rgb(0, 100, 0);\n"
            "    border-style: solid;  \n"
            "}\n"
            "\n"
            "QPushButton:checked{\n"
            "    border-width: 2px;  \n"
            "    background-color:rgb(40,80,40);\n"
            "    border-style: solid;  \n"
            "}\n"
            ""
        )
        self.AnalysisDialog_green_channel_button_visual.setCheckable(True)
        self.AnalysisDialog_green_channel_button_visual.setChecked(True)
        self.AnalysisDialog_green_channel_button_visual.setAutoExclusive(False)
        self.AnalysisDialog_green_channel_button_visual.setObjectName(
            "AnalysisDialog_green_channel_button_visual"
        )
        self.LayoutContainerForColorButtonsAnalysis.addWidget(
            self.AnalysisDialog_green_channel_button_visual, 0, 1, 1, 1
        )
        self.AnalysisDialog_red_channel_button_visual = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AnalysisDialog_red_channel_button_visual.sizePolicy().hasHeightForWidth()
        )
        self.AnalysisDialog_red_channel_button_visual.setSizePolicy(sizePolicy)
        self.AnalysisDialog_red_channel_button_visual.setMinimumSize(
            QtCore.QSize(44, 20)
        )
        self.AnalysisDialog_red_channel_button_visual.setMaximumSize(
            QtCore.QSize(75, 16777215)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AnalysisDialog_red_channel_button_visual.setFont(font)
        self.AnalysisDialog_red_channel_button_visual.setStyleSheet(
            "\n"
            "QPushButton{\n"
            "    color: rgb(255, 255, 255);\n"
            "    border-width: 2px;  \n"
            "    border-right-width: 0 px;\n"
            "    border-style: solid;  \n"
            "    border-radius: 10;  \n"
            "    padding: 3px;  \n"
            "    border-top-right-radius: 0;\n"
            "    border-bottom-right-radius: 0;\n"
            "    padding-left: 5px;  \n"
            "    padding-right: 5px;  \n"
            "    background-color: rgb(225, 0, 4);\n"
            "    border-color: rgb(20, 0, 0);\n"
            "    font-size: 19px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    border-width: 2px;  \n"
            "    border-color: rgb(100, 0, 0);\n"
            "    border-right-width: 0 px;\n"
            "    border-style: solid;  \n"
            "}\n"
            "\n"
            "QPushButton:checked{\n"
            "    border-width: 2px;  \n"
            "    background-color:rgb(80,40,40);\n"
            "    border-right-width: 0 px;\n"
            "    border-style: solid;  \n"
            "}\n"
            ""
        )
        self.AnalysisDialog_red_channel_button_visual.setCheckable(True)
        self.AnalysisDialog_red_channel_button_visual.setChecked(False)
        self.AnalysisDialog_red_channel_button_visual.setAutoExclusive(False)
        self.AnalysisDialog_red_channel_button_visual.setObjectName(
            "AnalysisDialog_red_channel_button_visual"
        )
        self.LayoutContainerForColorButtonsAnalysis.addWidget(
            self.AnalysisDialog_red_channel_button_visual, 0, 0, 1, 1
        )
        self.gridLayoutChannelsToMeasure.addLayout(
            self.LayoutContainerForColorButtonsAnalysis, 3, 0, 1, 1
        )
        self.parameters_label_channelsToMeasure = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.parameters_label_channelsToMeasure.setFont(font)
        self.parameters_label_channelsToMeasure.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.parameters_label_channelsToMeasure.setObjectName(
            "parameters_label_channelsToMeasure"
        )
        self.gridLayoutChannelsToMeasure.addWidget(
            self.parameters_label_channelsToMeasure, 0, 0, 1, 1
        )
        self.LayoutContainerForColorButtonsAnalysis_ch2 = QtWidgets.QGridLayout()
        self.LayoutContainerForColorButtonsAnalysis_ch2.setObjectName(
            "LayoutContainerForColorButtonsAnalysis_ch2"
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2 = (
            QtWidgets.QPushButton(Dialog)
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setEnabled(
            True
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.sizePolicy().hasHeightForWidth()
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setSizePolicy(
            sizePolicy
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setMinimumSize(
            QtCore.QSize(50, 20)
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setMaximumSize(
            QtCore.QSize(75, 16777215)
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setBaseSize(
            QtCore.QSize(0, 0)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setFont(font)
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setStyleSheet(
            "\n"
            "QPushButton{\n"
            "        color: rgb(255, 255, 255);\n"
            "\n"
            "             border-width: 2px;  \n"
            "            border-left-width: 0px;\n"
            "             border-style: solid;  \n"
            "             border-radius: 10;  \n"
            "             padding: 3px;  \n"
            "                border-top-left-radius: 0;\n"
            "                border-bottom-left-radius: 0;\n"
            "             padding-left: 5px;  \n"
            "             padding-right: 5px;  \n"
            "        background-color: rgb(5,5 , 255);\n"
            "        border-color: rgb(5, 5, 20);\n"
            "        font-size: 19px;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover{\n"
            "    border-width: 2px;  \n"
            "    border-color: rgb(0, 0, 200);\n"
            "    border-left-width: 0 px;\n"
            "    border-style: solid;  \n"
            "}\n"
            "\n"
            "QPushButton:checked{\n"
            "    border-width: 2px;  \n"
            "    background-color:rgb(40,40,80);\n"
            "    border-left-width: 0 px;\n"
            "    border-style: solid;  \n"
            "}\n"
            ""
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setCheckable(
            True
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setChecked(
            False
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setAutoExclusive(
            False
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setObjectName(
            "AnalysisDialog__blue_channel_button_visual_colocalization_ch2"
        )
        self.LayoutContainerForColorButtonsAnalysis_ch2.addWidget(
            self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2,
            0,
            2,
            1,
            1,
        )
        self.AnalysisDialog_green_channel_button_visual_ch2 = QtWidgets.QPushButton(
            Dialog
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AnalysisDialog_green_channel_button_visual_ch2.sizePolicy().hasHeightForWidth()
        )
        self.AnalysisDialog_green_channel_button_visual_ch2.setSizePolicy(sizePolicy)
        self.AnalysisDialog_green_channel_button_visual_ch2.setMinimumSize(
            QtCore.QSize(50, 24)
        )
        self.AnalysisDialog_green_channel_button_visual_ch2.setMaximumSize(
            QtCore.QSize(75, 16777215)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AnalysisDialog_green_channel_button_visual_ch2.setFont(font)
        self.AnalysisDialog_green_channel_button_visual_ch2.setStyleSheet(
            "\n"
            "QPushButton{\n"
            "            color: rgb(255, 255, 255);\n"
            "\n"
            "             border-width: 2px;  \n"
            "             border-style: solid;  \n"
            "             border-radius: 0;  \n"
            "             padding: 3px;  \n"
            "\n"
            "             padding-left: 5px;  \n"
            "             padding-right: 5px;  \n"
            "            background-color: rgb(5, 255, 5);\n"
            "            border-color: rgb(0, 20, 0);\n"
            "            font-size: 19px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    border-width: 2px;  \n"
            "    border-color: rgb(0, 100, 0);\n"
            "    border-style: solid;  \n"
            "}\n"
            "\n"
            "QPushButton:checked{\n"
            "    border-width: 2px;  \n"
            "    background-color:rgb(40,80,40);\n"
            "    border-style: solid;  \n"
            "}\n"
            ""
        )
        self.AnalysisDialog_green_channel_button_visual_ch2.setCheckable(True)
        self.AnalysisDialog_green_channel_button_visual_ch2.setChecked(True)
        self.AnalysisDialog_green_channel_button_visual_ch2.setAutoExclusive(False)
        self.AnalysisDialog_green_channel_button_visual_ch2.setObjectName(
            "AnalysisDialog_green_channel_button_visual_ch2"
        )
        self.LayoutContainerForColorButtonsAnalysis_ch2.addWidget(
            self.AnalysisDialog_green_channel_button_visual_ch2, 0, 1, 1, 1
        )
        self.AnalysisDialog_red_channel_button_visual_ch2 = QtWidgets.QPushButton(
            Dialog
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AnalysisDialog_red_channel_button_visual_ch2.sizePolicy().hasHeightForWidth()
        )
        self.AnalysisDialog_red_channel_button_visual_ch2.setSizePolicy(sizePolicy)
        self.AnalysisDialog_red_channel_button_visual_ch2.setMinimumSize(
            QtCore.QSize(44, 20)
        )
        self.AnalysisDialog_red_channel_button_visual_ch2.setMaximumSize(
            QtCore.QSize(75, 16777215)
        )
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AnalysisDialog_red_channel_button_visual_ch2.setFont(font)
        self.AnalysisDialog_red_channel_button_visual_ch2.setStyleSheet(
            "\n"
            "QPushButton{\n"
            "    color: rgb(255, 255, 255);\n"
            "    border-width: 2px;  \n"
            "    border-right-width: 0 px;\n"
            "    border-style: solid;  \n"
            "    border-radius: 10;  \n"
            "    padding: 3px;  \n"
            "    border-top-right-radius: 0;\n"
            "    border-bottom-right-radius: 0;\n"
            "    padding-left: 5px;  \n"
            "    padding-right: 5px;  \n"
            "    background-color: rgb(225, 0, 4);\n"
            "    border-color: rgb(20, 0, 0);\n"
            "    font-size: 19px;\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "    border-width: 2px;  \n"
            "    border-color: rgb(100, 0, 0);\n"
            "    border-right-width: 0 px;\n"
            "    border-style: solid;  \n"
            "}\n"
            "\n"
            "QPushButton:checked{\n"
            "    border-width: 2px;  \n"
            "    background-color:rgb(80,40,40);\n"
            "    border-right-width: 0 px;\n"
            "    border-style: solid;  \n"
            "}\n"
            ""
        )
        self.AnalysisDialog_red_channel_button_visual_ch2.setCheckable(True)
        self.AnalysisDialog_red_channel_button_visual_ch2.setChecked(False)
        self.AnalysisDialog_red_channel_button_visual_ch2.setAutoExclusive(False)
        self.AnalysisDialog_red_channel_button_visual_ch2.setObjectName(
            "AnalysisDialog_red_channel_button_visual_ch2"
        )
        self.LayoutContainerForColorButtonsAnalysis_ch2.addWidget(
            self.AnalysisDialog_red_channel_button_visual_ch2, 0, 0, 1, 1
        )
        self.gridLayoutChannelsToMeasure.addLayout(
            self.LayoutContainerForColorButtonsAnalysis_ch2, 5, 0, 1, 1
        )
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ComputeRatiosLabel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ComputeRatiosLabel.sizePolicy().hasHeightForWidth()
        )
        self.ComputeRatiosLabel.setSizePolicy(sizePolicy)
        self.ComputeRatiosLabel.setMinimumSize(QtCore.QSize(0, 16))
        self.ComputeRatiosLabel.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setFamily("Lato-light")
        font.setPointSize(10)
        self.ComputeRatiosLabel.setFont(font)
        self.ComputeRatiosLabel.setStyleSheet(
            "QLabel{\n"
            '    font-family:"Lato-light";\n'
            "    font-size: 11px;\n"
            "    border: 1px solid;\n"
            "    color: rgba(190, 190, 190,255);\n"
            "    border:0px solid;\n"
            "}\n"
            ""
        )
        self.ComputeRatiosLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ComputeRatiosLabel.setObjectName("ComputeRatiosLabel")
        self.gridLayout_2.addWidget(self.ComputeRatiosLabel, 0, 0, 1, 1)
        self.computeRatiosCheckBox = QtWidgets.QCheckBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.computeRatiosCheckBox.sizePolicy().hasHeightForWidth()
        )
        self.computeRatiosCheckBox.setSizePolicy(sizePolicy)
        self.computeRatiosCheckBox.setMaximumSize(QtCore.QSize(20, 16777215))
        self.computeRatiosCheckBox.setText("")
        self.computeRatiosCheckBox.setObjectName("computeRatiosCheckBox")
        self.gridLayout_2.addWidget(self.computeRatiosCheckBox, 0, 1, 1, 1)
        self.gridLayoutChannelsToMeasure.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayoutChannelsToMeasure, 2, 1, 4, 2)
        self.reset = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush
        )
        self.reset.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reset.setFont(font)
        self.reset.setObjectName("reset")
        self.gridLayout_6.addWidget(self.reset, 17, 1, 1, 1)
        self.next_image = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.next_image.setFont(font)
        self.next_image.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.next_image.setIconSize(QtCore.QSize(16, 17))
        self.next_image.setObjectName("next_image")
        self.gridLayout_6.addWidget(self.next_image, 5, 3, 1, 1)
        self.accept_changes = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.accept_changes.sizePolicy().hasHeightForWidth()
        )
        self.accept_changes.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush
        )
        gradient = QtGui.QLinearGradient(0.0, 0.0, 0.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(86, 86, 86))
        gradient.setColorAt(0.1, QtGui.QColor(82, 82, 82))
        gradient.setColorAt(0.5, QtGui.QColor(78, 78, 78))
        gradient.setColorAt(0.9, QtGui.QColor(74, 74, 74))
        gradient.setColorAt(1.0, QtGui.QColor(70, 70, 70))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush
        )
        self.accept_changes.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.accept_changes.setFont(font)
        self.accept_changes.setObjectName("accept_changes")
        self.gridLayout_6.addWidget(self.accept_changes, 17, 2, 1, 1)
        self.mask_groupbox = QtWidgets.QGroupBox(Dialog)
        self.mask_groupbox.setObjectName("mask_groupbox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.mask_groupbox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mask_size = QtWidgets.QLabel(self.mask_groupbox)
        self.mask_size.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mask_size.setObjectName("mask_size")
        self.gridLayout_4.addWidget(self.mask_size, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetNoConstraint
        )
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mask_size_sldr = QtWidgets.QSlider(self.mask_groupbox)
        self.mask_size_sldr.setMinimum(-50)
        self.mask_size_sldr.setMaximum(50)
        self.mask_size_sldr.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.mask_size_sldr.setObjectName("mask_size_sldr")
        self.verticalLayout_4.addWidget(self.mask_size_sldr)
        self.mask_shape_sldr = QtWidgets.QSlider(self.mask_groupbox)
        self.mask_shape_sldr.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.mask_shape_sldr.setObjectName("mask_shape_sldr")
        self.verticalLayout_4.addWidget(self.mask_shape_sldr)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 1, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mask_size_nmbr = QtWidgets.QSpinBox(self.mask_groupbox)
        self.mask_size_nmbr.setMinimum(-50)
        self.mask_size_nmbr.setMaximum(50)
        self.mask_size_nmbr.setObjectName("mask_size_nmbr")
        self.verticalLayout_3.addWidget(self.mask_size_nmbr)
        self.mask_shape_nmbr = QtWidgets.QSpinBox(self.mask_groupbox)
        self.mask_shape_nmbr.setObjectName("mask_shape_nmbr")
        self.verticalLayout_3.addWidget(self.mask_shape_nmbr)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 2, 2, 1)
        self.mask_shape = QtWidgets.QLabel(self.mask_groupbox)
        self.mask_shape.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mask_shape.setObjectName("mask_shape")
        self.gridLayout_4.addWidget(self.mask_shape, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.mask_groupbox, 13, 0, 1, 4)
        self.parameters_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.parameters_label.setFont(font)
        self.parameters_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.parameters_label.setObjectName("parameters_label")
        self.gridLayout_6.addWidget(self.parameters_label, 0, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_6.addItem(spacerItem, 18, 0, 1, 1)
        self.gridLayoutChannelToMeasure = QtWidgets.QGridLayout()
        self.gridLayoutChannelToMeasure.setSpacing(0)
        self.gridLayoutChannelToMeasure.setObjectName("gridLayoutChannelToMeasure")
        self.parameters_label_channelToMeasure = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.parameters_label_channelToMeasure.setFont(font)
        self.parameters_label_channelToMeasure.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.parameters_label_channelToMeasure.setObjectName(
            "parameters_label_channelToMeasure"
        )
        self.gridLayoutChannelToMeasure.addWidget(
            self.parameters_label_channelToMeasure, 0, 0, 1, 1
        )
        self.gridLayout_6.addLayout(self.gridLayoutChannelToMeasure, 1, 1, 1, 2)
        self.previous_condition = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.previous_condition.setFont(font)
        self.previous_condition.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight
        )
        self.previous_condition.setIconSize(QtCore.QSize(16, 17))
        self.previous_condition.setObjectName("previous_condition")
        self.gridLayout_6.addWidget(self.previous_condition, 4, 0, 1, 1)
        self.next_condition = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.next_condition.setFont(font)
        self.next_condition.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.next_condition.setIconSize(QtCore.QSize(16, 17))
        self.next_condition.setObjectName("next_condition")
        self.gridLayout_6.addWidget(self.next_condition, 4, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.contours_groupbox.setTitle(_translate("Dialog", "Contours"))
        self.edge_count_box.setText(_translate("Dialog", "Don't count points on edges"))
        self.strain_size_box.setText(_translate("Dialog", "Restrain size"))
        self.hightlight_manimum.setText(
            _translate("Dialog", "Highlight\n" " Minimum Size")
        )
        self.minimum_size_label.setText(_translate("Dialog", "Minimum size"))
        self.hightlight_maximum.setText(
            _translate("Dialog", "Highlight\n" " Maximum Size")
        )
        self.maximum_size_label.setText(_translate("Dialog", "Maximum Size"))
        self.ColocalizationGroupBox.setTitle(_translate("Dialog", "Colocalization"))
        self.MultipleColocMethodsLable.setText(
            _translate("Dialog", "Compute multiple colocalizations:")
        )
        __sortingEnabled = self.MultipleColocMethodsListWIdget.isSortingEnabled()
        self.MultipleColocMethodsListWIdget.setSortingEnabled(False)
        item = self.MultipleColocMethodsListWIdget.item(0)
        item.setText(_translate("Dialog", "Pearson's"))
        item = self.MultipleColocMethodsListWIdget.item(1)
        item.setText(_translate("Dialog", "Kendall’s tau"))
        item = self.MultipleColocMethodsListWIdget.item(2)
        item.setText(_translate("Dialog", "Mander's"))
        item = self.MultipleColocMethodsListWIdget.item(3)
        item.setText(_translate("Dialog", "Spearman's"))
        self.MultipleColocMethodsListWIdget.setSortingEnabled(__sortingEnabled)
        self.ComboboxOneMethodColoc.setItemText(0, _translate("Dialog", "Pearson"))
        self.ComboboxOneMethodColoc.setItemText(
            1, _translate("Dialog", " Kendall’s tau")
        )
        self.SingleColocMethodLabel.setText(_translate("Dialog", "Coloc. method :"))
        self.label.setText(_translate("Dialog", "Auto threshold"))
        self.bg_thresh_groupbox_2.setTitle(_translate("Dialog", "Channel 2"))
        self.substract_background_2.setText(
            _translate("Dialog", "Substract \n" "Background")
        )
        self.adjust_threshold_2.setText(_translate("Dialog", "Adjust \n" "Threshold"))
        self.bg_thresh_groupbox.setTitle(_translate("Dialog", "Channel 1"))
        self.substract_background.setText(
            _translate("Dialog", "Substract \n" "Background")
        )
        self.adjust_threshold.setText(_translate("Dialog", "Adjust \n" "Threshold"))
        self.previous_image.setText(_translate("Dialog", "<"))
        self.parameters_label_channel_2.setText(_translate("Dialog", "Channel 2"))
        self.parameters_label_channel_1.setText(_translate("Dialog", "Channel 1"))
        self.AnalysisDialog__blue_channel_button_visual_colocalization.setText(
            _translate("Dialog", "B")
        )
        self.AnalysisDialog_green_channel_button_visual.setText(
            _translate("Dialog", "G")
        )
        self.AnalysisDialog_red_channel_button_visual.setText(_translate("Dialog", "R"))
        self.parameters_label_channelsToMeasure.setText(
            _translate("Dialog", "Channels to measure")
        )
        self.AnalysisDialog__blue_channel_button_visual_colocalization_ch2.setText(
            _translate("Dialog", "B")
        )
        self.AnalysisDialog_green_channel_button_visual_ch2.setText(
            _translate("Dialog", "G")
        )
        self.AnalysisDialog_red_channel_button_visual_ch2.setText(
            _translate("Dialog", "R")
        )
        self.ComputeRatiosLabel.setText(_translate("Dialog", "Compute Ratios"))
        self.reset.setText(_translate("Dialog", "Cancel"))
        self.next_image.setText(_translate("Dialog", ">"))
        self.accept_changes.setText(_translate("Dialog", "Accept Chnages"))
        self.mask_groupbox.setTitle(_translate("Dialog", "Mask"))
        self.mask_size.setText(_translate("Dialog", "Mask Size"))
        self.mask_shape.setText(_translate("Dialog", "Mask shape"))
        self.parameters_label.setText(_translate("Dialog", "Parameters"))
        self.parameters_label_channelToMeasure.setText(
            _translate("Dialog", "Channel to measure")
        )
        self.previous_condition.setText(_translate("Dialog", "Previous\n" "Condition"))
        self.next_condition.setText(_translate("Dialog", "Next\n" "Condition"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
