# ../celer_sight_ai/UiAssets/OrganismSelectrionDiaolog.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogMainSelection(object):
    def setupUi(self, DialogMainSelection):
        DialogMainSelection.setObjectName("DialogMainSelection")
        DialogMainSelection.resize(1191, 691)
        DialogMainSelection.setStyleSheet("background-color: rgba(255,255,255,255)")
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogMainSelection)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainframe = QtWidgets.QFrame(parent=DialogMainSelection)
        self.mainframe.setMinimumSize(QtCore.QSize(0, 100))
        self.mainframe.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.mainframe.setStyleSheet("background-color:rgb(250,250,250);")
        self.mainframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainframe.setObjectName("mainframe")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mainframe)
        self.gridLayout_3.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint
        )
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.mainframe)
        self.frame.setMaximumSize(QtCore.QSize(60, 6000000))
        self.frame.setStyleSheet("background-color: rgb(140, 140, 140);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 11, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.pushButton.setStyleSheet(
            "background-color: rgba(100,100,100,255);\n" "border-radius:10;"
        )
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.pushButton_fly = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_fly.sizePolicy().hasHeightForWidth()
        )
        self.pushButton_fly.setSizePolicy(sizePolicy)
        self.pushButton_fly.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.pushButton_fly.setFont(font)
        self.pushButton_fly.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.pushButton_fly.setStyleSheet(
            "background-color: rgba(100,100,100,255);\n" "border-radius:10;"
        )
        self.pushButton_fly.setObjectName("pushButton_fly")
        self.gridLayout.addWidget(self.pushButton_fly, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 2, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.mainframe)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1148, 687))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.mainframe, 0, 0, 1, 1)

        self.retranslateUi(DialogMainSelection)
        QtCore.QMetaObject.connectSlotsByName(DialogMainSelection)

    def retranslateUi(self, DialogMainSelection):
        _translate = QtCore.QCoreApplication.translate
        DialogMainSelection.setWindowTitle(_translate("DialogMainSelection", "Dialog"))
        self.pushButton.setText(_translate("DialogMainSelection", "MD"))
        self.pushButton_fly.setText(_translate("DialogMainSelection", "Fly"))
