# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\manos\Documents\topfluov3\UiAssets\OrganismSelectrionDiaolog_tutorial.ui'
#
# Created by: PyQt6 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1135, 162)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 9, 0, 11)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        self.pg1_settings_contras_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pg1_settings_contras_label.sizePolicy().hasHeightForWidth()
        )
        self.pg1_settings_contras_label.setSizePolicy(sizePolicy)
        self.pg1_settings_contras_label.setMinimumSize(QtCore.QSize(0, 23))
        self.pg1_settings_contras_label.setMaximumSize(QtCore.QSize(16777215, 57))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(9)
        self.pg1_settings_contras_label.setFont(font)
        self.pg1_settings_contras_label.setStyleSheet(
            "QLabel{\n"
            '    font-family:"Lato";\n'
            "    font-size: 20px;\n"
            "    border: 1px solid;\n"
            "    color: rgba(60, 60, 60,255);\n"
            "    border:0px solid;\n"
            "    background-color:rgba(0,0,0,0);\n"
            "}\n"
            ""
        )
        self.pg1_settings_contras_label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignCenter
        )
        self.pg1_settings_contras_label.setObjectName("pg1_settings_contras_label")
        self.gridLayout.addWidget(self.pg1_settings_contras_label, 1, 0, 1, 3)
        self.CreateNewVButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.CreateNewVButton.sizePolicy().hasHeightForWidth()
        )
        self.CreateNewVButton.setSizePolicy(sizePolicy)
        self.CreateNewVButton.setMinimumSize(QtCore.QSize(130, 35))
        self.CreateNewVButton.setMaximumSize(QtCore.QSize(130, 35))
        self.CreateNewVButton.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.CreateNewVButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.CreateNewVButton.setStyleSheet(
            "QPushButton{\n"
            '    border-image: url("data/icons/icons_aa_tool/procced_nm_normal.png") 0 0 0 0 stretch stretch;\n'
            "\n"
            '    font-family:"Lato";\n'
            "    font-size: 19px;\n"
            "    border: 1px solid;\n"
            "    color: rgba(250, 250, 250,255);\n"
            "    border:0px solid;\n"
            "\n"
            "\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover{\n"
            '    border-image: url("data/icons/icons_aa_tool/procced_nm_hover.png") 0 0 0 0 stretch stretch;\n'
            "\n"
            "}"
        )
        self.CreateNewVButton.setObjectName("CreateNewVButton")
        self.gridLayout.addWidget(self.CreateNewVButton, 3, 1, 1, 1)
        self.pg_2_PlotParameteres_label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pg_2_PlotParameteres_label_3.sizePolicy().hasHeightForWidth()
        )
        self.pg_2_PlotParameteres_label_3.setSizePolicy(sizePolicy)
        self.pg_2_PlotParameteres_label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        self.pg_2_PlotParameteres_label_3.setFont(font)
        self.pg_2_PlotParameteres_label_3.setStyleSheet(
            '    font-family:"Lato";\n'
            "    font-size: 37px;\n"
            "color: rgb(5,5,5);\n"
            "border-radius:10px;\n"
            "margin-right:10px;\n"
            "margin-left:0px;\n"
            "background-color:rgba(0,0,0,0);"
        )
        self.pg_2_PlotParameteres_label_3.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignCenter
        )
        self.pg_2_PlotParameteres_label_3.setIndent(0)
        self.pg_2_PlotParameteres_label_3.setObjectName("pg_2_PlotParameteres_label_3")
        self.gridLayout.addWidget(self.pg_2_PlotParameteres_label_3, 0, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pg1_settings_contras_label.setText(
            _translate("Form", "To start, select nematodes, tissue or cells.")
        )
        self.CreateNewVButton.setText(_translate("Form", "Proceed"))
        self.pg_2_PlotParameteres_label_3.setText(
            _translate("Form", "Welcome to CelerSight AI")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
