# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\manos\Documents\topfluov3\UiAssets\scaledDialog.ui'
#
# Created by: PyQt6 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ScaleDialog(object):
    def setupUi(self, ScaleDialog):
        ScaleDialog.setObjectName("ScaleDialog")
        ScaleDialog.resize(247, 122)
        ScaleDialog.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.gridLayout = QtWidgets.QGridLayout(ScaleDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(ScaleDialog)
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setFrame(True)
        self.doubleSpinBox.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMaximum(1000000000000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(ScaleDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ScaleDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ScaleDialog)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 2)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(ScaleDialog)
        self.doubleSpinBox_2.setWrapping(False)
        self.doubleSpinBox_2.setFrame(True)
        self.doubleSpinBox_2.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons
        )
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(1000000000000.0)
        self.doubleSpinBox_2.setProperty("value", 1.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(ScaleDialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 2)

        self.retranslateUi(ScaleDialog)
        QtCore.QMetaObject.connectSlotsByName(ScaleDialog)

    def retranslateUi(self, ScaleDialog):
        _translate = QtCore.QCoreApplication.translate
        ScaleDialog.setWindowTitle(_translate("ScaleDialog", "Dialog"))
        self.label.setText(_translate("ScaleDialog", "Pixels per Unit"))
        self.label_2.setText(_translate("ScaleDialog", "Units"))
        self.pushButton.setText(_translate("ScaleDialog", "Get distance"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ScaleDialog = QtWidgets.QDialog()
    ui = Ui_ScaleDialog()
    ui.setupUi(ScaleDialog)
    ScaleDialog.show()
    sys.exit(app.exec())
